### ISSUE TITLE
Move utils into nowcasting_utils repo

### ISSUE THREAD

**Issue by JackKelly** [openclimatefix/nowcasting_dataset#100]
Metrics, plotting, etc?

https://github.com/openclimatefix/nowcasting_utils

**Comment by peterdudfield** [comment]
linked with https://github.com/openclimatefix/nowcasting_utils/issues/4

**Comment by peterdudfield** [comment]
metrics is done and plotting things are done 
- need to remove them from https://github.com/openclimatefix/predict_pv_yield

**Comment by peterdudfield** [comment]
Think this is done now
