### ISSUE TITLE
Remove conda installation instructions and remove `environment.yml`?

### ISSUE THREAD

**Issue by JackKelly** [openclimatefix/nowcasting_dataset#119]
At present, we're maintaining _two_ separate ways to install `nowcasting_dataset`:  through `pip` and through `conda`.  Should we simplify?  Should we delete all mention of `conda`?

To be specific:  At present, the code has a [`requirements.txt`](https://github.com/openclimatefix/nowcasting_dataset/blob/main/requirements.txt) (for `pip`) and an [`environment.yml`](https://github.com/openclimatefix/nowcasting_dataset/blob/main/environment.yml) (for conda, and uses Python 3.8).  The [README](https://github.com/openclimatefix/nowcasting_dataset/blob/main/README.md)'s installation instructions talk about using `conda` to install.  But the [`python-app.yml`](https://github.com/openclimatefix/nowcasting_dataset/blob/main/.github/workflows/python-app.yml) GitHub action uses `pip` with Python 3.9.

(Personally, I'm quite fond of conda.  But I recognise that pip is probably easier for most people; and easier for automated testing).

**Comment by jacobbieker** [comment]
I quite like conda too, and I think it works better for having an entirely reproducible environment for development, etc, while we need pip to make it easily installable for most potential users. So I'm not sure we need to remove one or the other. On the other hand, we could also standardize on conda, and add nowcasting, etc. to `conda-forge` so they are easily installable alongside all the other conda stuff.

**Comment by JackKelly** [comment]
Yeah, cool, I'd quite like to keep both `conda` and `pip` installation methods, too :)  (I prefer conda for my own dev environment, too)

Does anyone know if there's a way to automatically keep `requirements.txt` and `environment.yml` in sync?  :)

**Comment by jacobbieker** [comment]
We could have only the non-pip requirements in `environment.yml` and then all the pip things in `requirements.txt` it was what I was doing for SatFlow, so then installing it is only `conda create env -f environment.yml` then `pip install -r requirements.txt` for installing?

**Comment by JackKelly** [comment]
I'll close this issue for now as it feels like we do actually want to allow users to install via _either_ pip _or_ conda :)
