### ISSUE TITLE
Add test data to prepare_ml_data

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting_dataset#134]
## Detailed Description
Make sure the script prepare_ml_training_data.py also makes test data

## Context
Useful to have train, validation and test data

## Possible Implementation
append like validation

**Comment by JackKelly** [comment]
just to flag up that, strictly speaking, we're not allowed to redistribute the PVOutput.org PV data, or the NWP data.  But we're probably fine if you only use such a tiny amount of data in our test files that the data wouldn't threaten the revenue streams earned by PVOutput.org or the Met Office for selling their data!
