### ISSUE TITLE
"UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect."

### ISSUE THREAD

**Issue by JackKelly** [openclimatefix/nowcasting_dataset#154]
**Describe the bug**
When running `prepare_ml_data.py` I get this warning... 

> /home/jack/dev/ocf/nowcasting_dataset/nowcasting_dataset/data_sources/gsp/eso.py:67: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

If we're sure this is a false warning then let's silence the warning :)

**Comment by peterdudfield** [comment]
Yea I found this strange, as I had already used a function to move this to 'crs'. We could hind the comment in the script. I better way would be to open up a bug report on geopandas

**Comment by JackKelly** [comment]
I must admit I had to Google what a "geographic CRS" is :)

[It turns out that](https://www.earthdatascience.org/courses/use-data-open-source-python/intro-vector-data-python/spatial-data-vector-shapefiles/geographic-vs-projected-coordinate-reference-systems-python/) a _geographic_ CRS is a coordinate reference system which spans the entire globe (such as latitude & longitude) and hence might suffer from some local distortions (because Earth isn't a perfect sphere).  In contrast, a _projected_ CRS is one that only covers a bit of the globe, and hence can be better optimised to that region.

So I'd _guess_ this warning is saying that the centroid may be wrong by something like a few tens of meters because lat / lon is geographic CRS (and hence is slightly distorted).

TBH, when we're computing the centroid of each GSP region, we probably don't care about super-high accuracy:  We probably only need the centroid to be accurate to within a kilometre or so.  So I'd guess we can safely ignore this warning :)

@peterdudfield I remember you plotted some maps when you did this work originally.  Did your plots include the computed centroid super-imposed on the shape of the GSP?  And did the centroids look about right?!  If so, I guess we can be pretty confident that we can ignore this warning?

One solution maybe be to simply leave the shape file from ESO in its native [OSGB projection](https://epsg.io/27700) (instead of converting to lat/lon... i.e. on [line 108](https://github.com/openclimatefix/nowcasting_dataset/blob/main/nowcasting_dataset/data_sources/gsp/eso.py#L108), we'd remove `.to_crs(WGS84_CRS)`)?  OSGB is a "projected CRS".  [WGS84_CRS is another name for lat/lon](https://epsg.io/4326).

**Comment by peterdudfield** [comment]
Yea I saw that warning. I'm not too bothered by 10s of meters. The shape of the GSP is strange enough. 

Yea, I plotted them and it looks fine
![Alverdiscott](https://user-images.githubusercontent.com/34686298/134875603-126cab15-9e19-4723-9460-35cb20720dcc.png)
See [code](https://github.com/openclimatefix/nowcasting_dataset/blob/main/notebooks/2021-09/2021-09-14/gsp_centroid.py) to make more

**Comment by JackKelly** [comment]
yeah, I agree, I'm not worried about this warning!  That plot looks perfect :)

**Comment by peterdudfield** [comment]
Perhaps I can add a comment in the script, or near the bti where the warning appears. Just explaining that we will ignore this for the moment

**Comment by JackKelly** [comment]
That's a good first step.

Ultimately, we should probably get rid of the warning by either:

* using `warnings.filter` to silence the warning (although that can be dangerous); or
* Keep `geopandas` happy by passing it OSGB coordinates when computing the centroids

But there's no rush to do either of these things!  :)

**Comment by peterdudfield** [comment]
I solved it - good push from you to sort this out
