### ISSUE TITLE
`prepare_ml_data.py` should save separate logs to `OutputData.filepath/<SplitName>/<DataSource>`

### ISSUE THREAD

**Issue by JackKelly** [openclimatefix/nowcasting_dataset#156]
## Detailed Description
Save log to `OutputData.filepath` so that, in the future, it's possible to diagnose issues with the saved batches.

Also send log to the console.

**Comment by peterdudfield** [comment]
This would be handy

**Comment by JackKelly** [comment]
Now that each DataSource runs separately, it might make sense to save separate logs to `OutputData.filepath/<SplitName>/<DataSource>`

That will make it easier to diagnose errors specific to a data source.

(Perhaps _also_ save a unified log to `OutputData.filepath`)

**Comment by JackKelly** [comment]
I'm going to work on this now because it'll be useful to help diagnose issues with `nowcasting_dataset`...
