### ISSUE TITLE
Log git commit ID of nowcasting_dataset 

### ISSUE THREAD

**Issue by JackKelly** [openclimatefix/nowcasting_dataset#157]
So we can reproduce batches later if necessary and/or diagnose issues

**Comment by peterdudfield** [comment]
I did set up neptune.ai when running this. I think this gives the git commit for this. But perhaps the git commit should go into the 'confgiruation' file

**Comment by JackKelly** [comment]
Closed by PR #159

> I did set up neptune.ai when running this

Yeah, I really like the way neptune.ai logs useful stuff.  

But, I must admit I'm wondering if we can remove `neptune.ai` from `nowcasting_dataset`... I think `neptune.ai` is mostly about logging ML training runs.  Logging the details of each run of `prepare_ml_data.py` feels more like something we should log locally, along with the dataset itself... although, that said, I'm happy for `nowcasting_dataset` to continue logging to neptune (neptune is free for us!) if you find it useful!
