### ISSUE TITLE
Speed up unit tests

### ISSUE THREAD

**Issue by JackKelly** [openclimatefix/nowcasting_dataset#163]
## Detailed Description
`py.test` (on `leonardo`) takes 1 minute 42 seconds to run.  That's not bad, but it's always nice if the tests run in more like 10 seconds so we feel happy to run the tests after every change we make to the code during development.

I think the two longest-running tests are `test_gsp_data_source.py` and `test_pv_data_source.py`.

Not hugely urgent though!  And, no worries if it's not possible to shorten the runtime of some tests.  Maybe we could have a subset of tests which run if we do `py.test --quick` (which we'd run after every change to the code) and then we'd run `py.test` to run the full test suite before committing?

**Comment by peterdudfield** [comment]
Ive speed up the tests, and there was actually a fix that was needed. Have not done the --quick option

**Comment by JackKelly** [comment]
Awesome, thanks!  I'll see how long the tests take to run on `leonardo` later today...

**Comment by peterdudfield** [comment]
any faster?

**Comment by JackKelly** [comment]
Ah, sorry, I haven't tested recently (and, if I do it now, it'll probably be slowed down by `leonardo` copying data at 800 MB/sec between two RAID arrays!)  Let's mark this as closed for now, as I'm pretty sure your speed-up to the PVDataSource tests should solve the issue.  I'll re-open if the tests aren't running faster!  Thanks!
