### ISSUE TITLE
Modify `SatelliteDataSource` so it can load from EUMETSAT's native files

### ISSUE THREAD

**Issue by JackKelly** [openclimatefix/nowcasting_dataset#176]
## Detailed Description
Give users the option of either loading from intermediate Zarr files or reading directly from EUMETSAT native files, (separately downloaded by #91).

This is a sub-task of #90.

## Possible Implementation
Maybe the `SatelliteDataSource` constructor would take an `engine` argument which would be set to `zarr intermediate` or `EUMETSAT native` or something like that.  Under the hood, we might want two subclasses of `SatelliteDataSource`: one for loading intermediate Zarr files, another for loading raw EUMETSAT data.

To load native EUMETSAT files, we maybe want to write a thin wrapper around the files which can do things like:

* Return the datetime index of all available files on disk
* Return a satellite image for a given time and geographical location

Related to (but separate from) issue #92

**Comment by JackKelly** [comment]
I'll start working on this today.

I'm super-impressed at how [Satpy](https://satpy.readthedocs.io/) has matured and advanced since [I last used Satpy a couple of years ago](https://github.com/openclimatefix/satellite_image_processing)!

**Comment by JackKelly** [comment]
Advice from @jacobbieker :+1: 

* Turn off enhanced (on satpy) so it doesn't stretch the values
* Leave the calibration _on_ (which converts from raw pixel values to radiance)

**Comment by jacobbieker** [comment]
One other idea, its not native files directly though, could be to resave the native files to GeoTIFF, if we can't only load part of the native files. I believe we wouldn't lose any information, and is as close to native as we can probably get as well, while then allowing us to subselect data easily from all the files. It'd be easy enough to add to the download script from #172 too

**Comment by JackKelly** [comment]
Sounds good!

Can GeoTIFF store all the metadata from the `native` files?  If not, saving each `native` file as a NetCDF file might be an alternative.  I'll do some benchmarking / experimenting.

**Comment by jacobbieker** [comment]
I think so? GeoTiff will store the projection, transformation, and data, I don't think it would by default store the satellite `orbital_parameters` but would everything else

**Comment by JackKelly** [comment]
Actually, it turns out someone has already asked the question on the SatPy issue queue: https://github.com/pytroll/satpy/issues/1732

If I've understood correctly, that 0.38 seconds per timestep doesn't actually load any data into memory (just loads the metadata).  Instead `.load()` lazily opens a dask array, and the actual data isn't loaded off disk until the processing is done.

OK, I think I've convinced myself that loading `.native` files directly into `nowcasting_dataset` will be _way_ too slow.  We need an intermediate step.  I'll open a new issue for the design and implementation of the intermediate step.
