### ISSUE TITLE
CI - takes a long time - requirements

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting_dataset#177]
**Describe the bug**
CI - github actions takes a long time to install requirements
https://github.com/openclimatefix/nowcasting_dataset/runs/3741632807?check_suite_focus=true

Seems to be an error with 'rioxarray'

**Expected behavior**
Should take about ~2/3 mins

**Additional context**
I think this new package 'rioxarray' came in with the topological data  (@jacobbieker ?)

**Comment by jacobbieker** [comment]
Yeah, its using rioxarray for the GeoTIFF reading and resampling, as Xarray itself doesn't have great support for spatial resampling.

**Comment by peterdudfield** [comment]
There seems to be a funny error message
<img width="1098" alt="Screenshot 2021-09-29 at 10 09 41" src="https://user-images.githubusercontent.com/34686298/135239024-494e6aaa-df3b-4aaa-b8d7-8def2651f560.png">
e 

Maybe numpy needs to be installed first?

**Comment by JackKelly** [comment]
`pip` has been causing a couple of problems for the CI.  Should we use `conda` to install the dependencies on the CI server?  (_can_ we use conda on GitHub Actions?!)

**Comment by jacobbieker** [comment]
Yeah, we can use conda, there are a few GH templates for it I think, one [here](https://github.com/marketplace/actions/setup-conda)

**Comment by jacobbieker** [comment]
The advantage of using it with `pip` is that it can ensure that the pip packages work and have all the required dependencies, etc.

**Comment by jacobbieker** [comment]
> There seems to be a funny error message <img alt="Screenshot 2021-09-29 at 10 09 41" width="1098" src="https://user-images.githubusercontent.com/34686298/135239024-494e6aaa-df3b-4aaa-b8d7-8def2651f560.png"> e
> 
> Maybe numpy needs to be installed first?

Numpy is installed first, as its before it in the `requirements.txt` so not really sure why that is happening

**Comment by JackKelly** [comment]
Cool, no worries, I have no strong opinions of whether we should use `pip` or `conda` for CI!  I guess `conda` can take a while to install itself, and then to install the Python packages.

But, that said, after using `conda` almost exclusively for the past few years, I'm surprised and a little disappointed that `pip` seems so fragile and sensitive to the ordering of the `requirements.txt`!

**Comment by peterdudfield** [comment]
yea, im suprised too. 

I think its more common just to have a list of requirements, and then people can install them how they want. And that can be in using pip or conda. Is that right?

**Comment by JackKelly** [comment]
I'm honestly not sure what's the correct way to have both a `requirements.txt` and an `environment.yml`.  The way we do it at the moment kind of works, where we do:

```shell
conda env create -f environment.yml` and then do
conda activate nowcasting_dataset
pip install -e . 
```

But that results in `pip` rudely replacing some packages behind `conda`'s back, which probably isn't ideal :)

**Comment by peterdudfield** [comment]
I'll close this for the moment
