### ISSUE TITLE
Normalize data by install capacity on 1st January 2021

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting_dataset#182]
## Detailed Description
Normalize GPS data by install capacity. 

## Context
Good to normalize data, 
and need to make sure know how to un-normalize later

## Possible Implementation
get install capacity from pvlive api

**Comment by JackKelly** [comment]
Sounds good!

Maybe, later, it would also be nice to have the option to normalise by the installed capacity at the time (e.g., for 2016 data we'd normalise by the capacity of installed PV in 2016)... but maybe that's a follow-on...  Any thoughts?

**Comment by peterdudfield** [comment]
Yea, tricky problem, that might actually be significant to results. 

It might be fairly simple to normalise by capacity when its installed, because that data can be pulled quite easily. This would be all the data is normalise by the correct amount, and for predicting we can use the most update to data, to de-noramlise

**Comment by peterdudfield** [comment]
So the map would be useful, for see, this sites are in cloud, these are not, so only predict 50%. 
I think that can be an additional thing to add, and shouldn't affect the normalization ... ?

**Comment by JackKelly** [comment]
> I think that can be an additional thing to add, and shouldn't affect the normalization

Yeah, exactly (sorry, I was taking us a bit off-topic!)  I'll create a new GitHub issue about adding a map of installed PV...

**Comment by peterdudfield** [comment]
> > I think that can be an additional thing to add, and shouldn't affect the normalization
> 
> Yeah, exactly (sorry, I was taking us a bit off-topic!) I'll create a new GitHub issue about adding a map of installed PV...

No all good - good to discuss this things. I'm sometimes alwasy up for making sure issues are independent as much as possible
