### ISSUE TITLE
Tidy generation data scripts with configruation

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting_dataset#186]
## Detailed Description
Use a configuration file to get details for running collection fo raw data
see https://github.com/openclimatefix/nowcasting_dataset/blob/main/scripts/get_raw_pv_gsp_data.py
and other generation data files

## Context
This keeps things tidy

## Possible Implementation
use `config = load_yaml_configuration(filename)`

**Comment by peterdudfield** [comment]
This still used? https://github.com/openclimatefix/nowcasting_dataset/blob/main/scripts/rechunk_nwp_data.py @JackKelly

**Comment by JackKelly** [comment]
I think the following scripts are safe to delete, if you guys (@jacobbieker & @peterdudfield ) agree:

* rechunk_nwp_data.py
* rechunk_sat_data.py

And I'd suggest moving `get_raw_eumetsat_data.py` over to the `satip` repo, maybe?  What do you think, @jacobbieker?  Then folks who want to download EUMETSAT data (but have no interest in `nowcasting_dataset` can use `get_raw_eumetsat_data.py`.

**Comment by jacobbieker** [comment]
Yeah, I was meaning to move that eumetsat data over as well. Then we can get rid of any dependency on Satip or SatPy in nowcasting_dataset. As for the other two scripts, I've never used them so feel free to delete!
