### ISSUE TITLE
Can we simplify the code by always keeping the data in one data type (e.g. xr.DataArray) per modality?

### ISSUE THREAD

**Issue by JackKelly** [openclimatefix/nowcasting_dataset#209]
In the past, `nowcasting_dataset` was designed to feed data on-the-fly into a PyTorch model.  Which meant that, as the data flowed through `nowcasting_dataset`, the data would change type:  For example, satellite data would start as an `xr.DataArray`, then get turned into a `numpy array` (because PyTorch doesn't know what to do with an `xr.DataArray`), and then get turned into a `torch.Tensor`.

But, I think we can safely say now that `nowcasting_dataset` is _just_ for pre-preparing batches (_not_ for loading data on-the-fly).  As such, we can probably simplify the code by keeping data in a single container type per modality.  For example, satellite data could _always_ live in an `xr.DataArray` for its entire life while flowing through `nowcasting_dataset`.

Sorry, I really should've thought of this earlier!  But, yeah, I think this could simplify the code quite a lot.

I haven't fully thought through the implications of this, but some changes might be:

* In the Pydantic models, each field can be just a _single_ type (instead of a `Union` of types).  So, for example, instead of `sat_data: Array = Field(...` we can just do `sat_data: xr.DataArray = Field(...`
* We can get rid of the `to_numpy` function.
* For all the modalities which use xarray of pandas data types, we can use dimension _names_ instead of _indexes_.  e.g. `seq_length = len(sat_data[-4])` becomes `seq_length = len(sat_data.time)`
* Saving and load data to/from disk becomes super-simple.
* We'd no longer need the `to_xr_dataset` and `from_xr_dataset` methods (which are quite fiddly)

**Comment by JackKelly** [comment]
Before we can fully implement this, #86 probably needs to be implemented

**Comment by peterdudfield** [comment]
Looks like you would still need a to_tensor() function that moves the xr datasets to tensors

https://github.com/openclimatefix/nowcasting_dataset/blob/peter/explore/notebooks/2021-10/2021-10-11/xr_tensor.py

Unless there is a better way?

**Comment by JackKelly** [comment]
Yes, I agree, we'd definitely still need a `to_tensor()` function to go from `xr.Dataset` to `torch.Tensor` :) 

I've been updating issue #25 with some notes about that; and your approach looks good to me, @peterdudfield !

**Comment by JackKelly** [comment]
Looks good!

Another simplification that we might be able to make is to _only_ represent batches (#212).   In other words, we could drop the idea of representing individual "examples" :slightly_smiling_face:.   I haven't fully thought this through but I think that it was only necessary to represent individual examples back when we wanted `nowcasting_dataset` to _combine_ multiple modalities into a single batch during pre-processing.  But, once #202 is implemented, I think we may be able to move to a world where each `DataSource` _only_ loads entire batches for pre-processing :slightly_smiling_face: 

So, in your ipython notebook, we might be able to drop `SatelliteBatch` becuase `Satellite` will _always_ represents a whole batch of satellite data :)

Does that sound OK?  Or have I gotten myself confused?!

**Comment by peterdudfield** [comment]
That does make sense, 

yea I would expect each 'datasource' to make a BatchObject and save it to a file. So in that case 'Satellite' could be ignored. 

I agree Example wont really be needed, in this ml pipeline. 
But it might be useful to have this for visualisation. I kinda of like the idea of showing the whole example and try understanding to see the behaviour
