### ISSUE TITLE
"Big new design" for nowcasting_dataset

### ISSUE THREAD

**Issue by JackKelly** [openclimatefix/nowcasting_dataset#213]
## Detailed Description
Over the last few weeks, we've come up with a bunch of ideas for how to simplify nowcasting_dataset.

This issue exists to keep track of all of those "new design" issues and to discuss how these individual issues hang together into a single coherent design; and to discuss how to implement this new design in a sequence of easy-to-digest chunks :)

The plan:

In terms of sequencing this work, I'm now thinking I'll do something along the lines of this:

First, do some stand-alone "preparatory" work.  Specifically:

- [x] #204 
- [x] #217 
- [x] #223 
- [x] #270
- [x] #299

Implement and write tests for some of the functions in the draft design in the GitHub comment below.  (for now, these functions won't actually be called in the code):

- [x] `sample_spatial_and_temporal_locations_for_examples()`  (done in PR #278)
- [ ] `DataSource.prepare_batches()`

Then, the big one (where the code size will hopefully shrink a lot!): 
- [ ] Re-write `prepare_ml_data.py` so it looks like the sketch above.  Use `click` to pass in command-line params.
- [ ] implement the remaining utility functions
- [x] #298
- [ ] delete the unnecessary code,
- [x] #86
- [ ] #170 
- [ ] Remove `n_timesteps_per_batch`?
- [ ] Stop using the first entry in `DataSourceList` as the one which defines the geospatial location of each example.
- [ ] Search through the code for TODOs associated with issues associated with this big design change.
- [ ]  #277 
- [ ] Document the new architecture.  Ideally with a diagram :slightly_smiling_face: 
- [ ] #293
- [x] #135 

Remove:
- [ ] All of `dataset/datamodule.py`
- [ ] `dataset.datasets.NowcastingDataset`
- [ ] `dataset.datasets.worker_init_fn()`
- [ ] All the `batch_to_dataset` and `dataset_to_batch` stuff
- [ ] All the `to_numpy` and `from_numpy` stuff (assuming we can go straight from `xr.Dataset` to `torch.Tensor`)

## Related issues

- [x] #211 
- [x] #209 
- [x] #202 
- [x] #166
- [x] #230
- [ ] #212 
- [ ] #208
- [x] #204 
- [x] #97 
- [ ] #48 
- [ ] #25 
- [ ] #219
- [ ] #170 

## A bit more context

I think I've made our lives far harder than they need to be by trying to support two different use-cases: 

1. Loading training data on-the-fly from multiple Zarr files during ML training; and 
2. Pre-preparing batches.

I think we can make life _way_ easier by dropping support for use-case 1  :)

Here's the broad proposal that it'd be great to discuss:

We drop support for loading data directly from Zarr on-the-fly during ML training (which we haven't done for months, and - now that we're using large NWP images - it would be far too slow).  nowcasting_dataset becomes laser-focused on pre-preparing batches (just as we use it now).

This allows us to completely rip out PyTorch from nowcasting_dataset (#86); and enables each "modality" to stays in a single data type throughout nowcasting_dataset (#209).  e.g. Satellite data stays in an `xr.Dataset`.  Each modality would be processed concurrently in different processes; and would be output into different directories (e.g. `train/satellite/` and `train/nwp/`) (#202).

Inspired by and making use of @peterdudfield's Pydantic PR (#195), we'd have a formal schema for the data structures in nowcasting_dataset (#211).

The ultimate aim is to simplify the code (I'm lazy!), whilst keeping all the useful functionality, and making the code easier to extend & maintain :slightly_smiling_face:

Of course, we'll still use a pytorch dataloader to load the pre-prepared batches off disk into an ML model.  But that's fine; and should work in very a similar (maybe identical?) fashion to how it works now :slightly_smiling_face:

I certainly can't claim to have thought this all through properly!  And everything's up for discussion, of course!

**Comment by peterdudfield** [comment]
Great work @JackKelly putting this all together. I think this will be super useful at making a really solid base for our ML learning problems we are trying to solve. 

I'm slightly biased by 1. , but yea I would do 1. first. #195 
2. #202 then is a good next logic step. I would be tempted to split this into two tasks. 
A. Change current save to netcdf to save several files. B. Change core code sot hat it can run in different processes. Doing A, first will allows us to remake datasets more easily, and just copy the ones that are the same from previous versions. 
3. 4. Perhaps this can be done at the same time. I feel like doing #209 first gives us a quicker win, and makes things simpler. 
5. Then #211 will be a nice bonus on the end.

I'll just share my thoughts on how #209 can be done, that allows data to end up as numpy / tensor values
<img width="1011" alt="Screenshot 2021-10-09 at 20 58 35" src="https://user-images.githubusercontent.com/34686298/136672343-c32a2ac4-10c0-48e4-a3a4-fb49f6ab2c42.png">

**Comment by JackKelly** [comment]
I love the idea of re-using stuff!

But, a few thoughts and questions about doing `x = Batch(**x)` inside `forward(x)`:

1. Does converting `x` from a `dict` to a `Batch` help make our code more readable?  My expectation is that, within `forward(x)`, `x` will be a `Dict[str, Tensor]`.  So, as is the case now, we'll be able to write human-readable code like `x['satellite']` to get the satellite data.
2. I'd be a bit worried that this will force PyTorch to move the data from GPU memory (when `x` is a `dict[str, Tensor]`), to CPU system memory (when `x` is a `Batch` and is being validated by Pydantic), and back to GPU memory for training.  That may slow training down because the PCIe bus is _way_ slower than the GPU's memory bus.
3. Pydantic's validation logic may slow down the training loop.  I'd advocate for doing all our data validation when we prepare the training batches. Then, during the training loop, we should just trust that the data has already been validated :slightly_smiling_face: .  I agree that's perhaps as not as belt-and-braces as validating the data multiple times, but hopefully it's sufficient to validate the data once (when we pre-prepare the ML batches).

What do you think?

**Comment by JackKelly** [comment]
Sure, sounds good, thanks loads for doing the test!  That's super-useful.  (Yay for empirically testing stuff!)  Let's go for it!

**Comment by peterdudfield** [comment]
Here's a useful method to covert a xr.Dataset to dictionary of torch items
![Screenshot 2021-10-13 at 09 40 27](https://user-images.githubusercontent.com/34686298/137098689-7e1f71ec-37c5-4c42-a207-bc822d59233f.png)

**Comment by JackKelly** [comment]
This design looks great to me!

Please do implement this now in a branch other than `main`.

But, unless I've misunderstood, the code in `main` (as at stands right now) is incompatible with this design, because, right now, the code in `main` forces each modality to change data type multiple times as it passes through the code (e.g. satellite data starts as an xarray object, then numpy, then a tensor, and finally into the pytorch DataLoader).  So Pydantic may complain when `Batch.satellite` stops being an instance of `class Satellite(xr.Dataset)` and gets turned into a numpy array, for example.  (Or maybe it'll be fine as long as the satellite data is an instance of `class Satellite(xr.Dataset)` _at the time that `Batch` is instantiated_: maybe Pydantic won't notice if the `Batch.satellite` data subsequently changes to a numpy array?

I plan to rip out the `pytorch DataLoader` over the next few days.  So, hopefully, by the end of the week the code will be fully compatible with your design!  So, yeah, if you go ahead and implement it in a new branch, while this is on your mind, then hopefully we can merge it later in the week once I've completely finished #86 and have implemented the design I sketched out in https://github.com/openclimatefix/nowcasting_dataset/issues/213#issuecomment-940153782 above :slightly_smiling_face:.  

Or have I misunderstood?  :slightly_smiling_face:

**Comment by JackKelly** [comment]
Cool beans, all sounds great!  Thank you!  I'm genuinely excited to see `nowcasting_dataset` really mature and become well-designed and easy to modify - thank you for all your work!
