### ISSUE TITLE
Tweak the way DataSources are represented in the Configuration model

### ISSUE THREAD

**Issue by JackKelly** [openclimatefix/nowcasting_dataset#217]
## Detailed Description
We maybe want to make a few small changes to the Configuration model:
- include a list of `enabled_data_sources`
- maybe split the config up so each data source has its own section, so that entire section can be passed into the DataSource object.  e.g. there would be an `NWP` section,  with fields zarr_path, image_size, and channels.

## Context
Splitting up the Configuration so each data source has its own section should mean that we don't have to write custom code to translate between a Configuration object and the constructor for each DataSource.  Instead we just do something like `SatDataSource(**config.sat_data)`

**Comment by peterdudfield** [comment]
That would be very neat indeed
