### ISSUE TITLE
Remove time_30 and time_5

### ISSUE THREAD

**Issue by JackKelly** [openclimatefix/nowcasting_dataset#230]
After #223 is implemented, the code should be able to handle any arbitrary sample rate. And, once we output each modality into a different NetCDF file, each NetCDF file will have a single sample period. So always refer to time as `time` and remove any code that talks about time_5 or time_30

**Comment by peterdudfield** [comment]
This is covered in 
https://github.com/openclimatefix/nowcasting_dataset/pull/229
