### ISSUE TITLE
Move all data normalisation to nowcasting_dataloader

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting_dataset#231]
## Detailed Description
Currently satellite normalisation can happen in two places
 - https://github.com/openclimatefix/nowcasting_dataset/blob/main/nowcasting_dataset/data_sources/satellite/satellite_data_source.py#L186
 - https://github.com/openclimatefix/nowcasting_dataset/blob/main/nowcasting_dataset/dataset/datasets.py#L210

## Context
- Dont want to do it twice, as this may lead to funny ML problems
- Would be nice if the metadata stored if the data had been normalised or not. 
- Nice to have it un normalised in batches too, so it can be displayed easily

## Possible Implementation
Only have option to do it once. 
- It could be a submethod of one of the Satellite classes. 
- The metadata stored if the data had been normalised or not, then we know what has been done

**Comment by JackKelly** [comment]
This all sounds great!

I agree, maybe `nowcasting_dataset` shouldn't do _any_ normalisation (which also makes the `nowcasting_dataset` code easier!).  Instead, all data normalisation can be done on-the-fly in `nowcasting_dataloader`.

**Comment by peterdudfield** [comment]
Or maybe its ok just to have a rough number for this. Its only normalised for the purpose of the ML model right?

**Comment by jacobbieker** [comment]
There is also normalization in `nowcasting-utils` here: https://github.com/openclimatefix/nowcasting_utils/blob/main/nowcasting_utils/models/normalization.py incase we want to have all of our normalization code in the same place

**Comment by JackKelly** [comment]
Cool beans, thank you, sorry I'm a bit behind the curve!

**Comment by JackKelly** [comment]
Is all the normalisation code moved from `nowcasting_dataset` (and data prep scripts) to `nowcasting_dataloader`, now?  (i.e.: can we close this issue now?!  :slightly_smiling_face: )

**Comment by peterdudfield** [comment]
Gsp and PV is not

**Comment by peterdudfield** [comment]
GSP is probably quite easy to do, but PV might be a longer.

**Comment by peterdudfield** [comment]
Ill do GSP first

**Comment by JackKelly** [comment]
SGTM, thanks!
