### ISSUE TITLE
Save the GSP names in `pv_gsp.zarr` 

### ISSUE THREAD

**Issue by JackKelly** [openclimatefix/nowcasting_dataset#240]
## Detailed Description
Sheffield Solar's API uses numerical "GSP IDs" (1, 2, 3, etc.).  These numerical GSP IDs are saved into our `pv_gsp.zarr` store.

It would be great if the `pv_gsp.zarr` included metadata which mapped from the numerical GSP IDs to string GSP names (like `BICF_1`)

Specifically, we could get the metadata using `nowcasting_dataset.data_sources.gsp.eso.get_gsp_metadata_from_eso(calculate_centroid=False)`.  And the minimum, we could save a mapping from `gsp_id` to `gsp_name`.  But we could just save all the metadata into `pv_gsp.zarr`.

Also, while doing this, it might be good to use ints for the "gsp_id" in `pv_gsp.zarr` (they are currently strings: `['1', '2', ...]`)

## Context

Textual GSP names are necessary to allow us to align the Sheffield Solar PV Live Regional data with the GSP-level PV forecasts we received from ESO (which use textual IDs for each GSP).  And, when we report the performance of our GSP-level PV nowcasts, ESO will probably want us to use textual GSP names.

**Comment by peterdudfield** [comment]
Its easy to change strings to integers so maybe ill do that, with v2 of gsp data

**Comment by peterdudfield** [comment]
perhaps we should close this for now? If we are happy that names dont go into the zarr file

**Comment by JackKelly** [comment]
good points, let's close this for now
