### ISSUE TITLE
Multi process when saving to netcdf

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting_dataset#244]
## Detailed Description
Use threading/ mulit cpu when saving batch to netcdf

## Context
This will speed up saving to netcdf

## Possible Implementation
loop [here](https://github.com/openclimatefix/nowcasting_dataset/blob/main/nowcasting_dataset/dataset/batch.py#L133)

**Comment by JackKelly** [comment]
Good point!  That should happen "naturally" as part of #202 (and, in 202, we can use multiple processes per modality)
