### ISSUE TITLE
Investigate why there are sometimes multiple GSPs at one location

### ISSUE THREAD

**Issue by JackKelly** [openclimatefix/nowcasting_dataset#272]
To quote the comments in `GSPDataSource.get_locations_for_batch()`: 

```python
# Make sure there is only one. Sometimes there are multiple gsp_ids at one location
# e.g. 'SELL_1'. Further investigation on this may be needed,
# but going to ignore this for now.  
metadata_for_gsp = meta_data.iloc[0]
```

We should investigate this further!  My guess is because there isn't a nice clean 1:1 mapping between region IDs and GSP names.

**Comment by peterdudfield** [comment]
Weird things to do with gnodes and GSPs, but this will be solves tihe the 2022-07-19th update to PV live. Ill close this for the moment
