### ISSUE TITLE
Normalise sat channels correctly

### ISSUE THREAD

**Issue by JackKelly** [openclimatefix/nowcasting_dataset#28]
Prob best to do it in the SatelliteDataSource, because it knows which channels are loaded.

**Comment by JackKelly** [comment]
Maybe do this using `transforms.Normalize`.  But how to get the correct normalisation params for the specific set of channels?  Maybe wrap `transforms.Normalize` in some code that looks at the list of channels in the xarray dataset passed in?

**Comment by jacobbieker** [comment]
How I do it is just have a dict of the mean and stddev using the satellite channel names, and then normalize based off which bands the model is training on https://github.com/openclimatefix/satflow/pull/35/commits/18c126cbe6b49b2c6f9c841f95b21e9b066f9bf1 So more like your second option

**Comment by JackKelly** [comment]
Nice!  Sounds like a great approach!  I'll do that :)
