### ISSUE TITLE
Throw an error if any config YAML fieldnames are unrecognised

### ISSUE THREAD

**Issue by JackKelly** [openclimatefix/nowcasting_dataset#288]
## Detailed Description
At present, the code just silently ignores any incorrect fieldnames.  (e.g. if you incorrectly spell `satellite_zarr_path` as, say, `satelite_zarr_path` then it will silently ignore `satelite_zarr_path` and use the default values).

**Comment by peterdudfield** [comment]
One way would be not to have a default value, then you would have to enter this value. But I kinda of like the default values.

**Comment by JackKelly** [comment]
Yeah, I've been wondering about the default values, too!  

A downside of the default values is it becomes all too easy to silently configure `nowcasting_dataset` to something we didn't mean to configure (e.g. using the wrong number of timesteps.  Or one thing that's got me in the past is silently loading completely the wrong Zarr store!)

But, on the other hand, I agree that the default values are kind of useful :slightly_smiling_face:

**Comment by peterdudfield** [comment]
Perhaps there is still a way to check on keys in the yaml file are valid ... need to look into it more. Then we could still ahve default values, but just check the yaml file is correct

**Comment by peterdudfield** [comment]
someone did it like this - https://github.com/samuelcolvin/pydantic/issues/2285

**Comment by peterdudfield** [comment]
``` 
class Base(pydantic.BaseModel):
    class Config:
        extra = 'forbid'   # forbid use of extra kwargs
```
might has work
