### ISSUE TITLE
In DataSource, remove underscore from _total_seq_length, _history_duration, _forecast_duration, and _total_seq_duration

### ISSUE THREAD

**Issue by JackKelly** [openclimatefix/nowcasting_dataset#292]
https://github.com/openclimatefix/nowcasting_dataset/blob/main/nowcasting_dataset/data_sources/data_source.py#L62

Use `grep -r --include=*.py "_total_seq_length"` to find other places in the code where these variables are used.

**Comment by lenassero** [comment]
Hi, I am taking a look at the good first issues :) 
I guess this can be closed as it has been fixed in #350 and #351 ?

**Comment by JackKelly** [comment]
Thanks loads for taking a look at our "good first issues"!

Good catch!  This issue has indeed been closed by #350 and #351.  I'll close this issue now!  Thank you!
