### ISSUE TITLE
Save `history_length` and `forecast_length` to disk for each modality, and use these in dataloader

### ISSUE THREAD

**Issue by JackKelly** [openclimatefix/nowcasting_dataset#293]
When we use different sample frequencies and/or different durations for each modailty, then our ML code will need to know the `history_length` and `forecast_length` for each modailty, in order to work out what's in the past and what's in the future :slightly_smiling_face:

**Comment by peterdudfield** [comment]
think this is now done

**Comment by JackKelly** [comment]
OK, cool, thanks for the update... Please do close this issue if you're sure :slightly_smiling_face:
