### ISSUE TITLE
Update Satellite Zarr reader for new format

### ISSUE THREAD

**Issue by jacobbieker** [openclimatefix/nowcasting_dataset#313]
## Detailed Description
Satellite data is now stored in the zarr in unprojected format, so the original geo projection. This does make it slightly more difficult to save the OSGB coordinates in the zarr, as each pixel has a unique OSGB x and y coordinate. Currently, they are stored in the metadata field, under 'osgb_x' and 'osgb_y'. There might be a better way to store it, which we could also do, but for now, we probably need to read in the metadata of one example each for the HRV channel and all the other channels, to get the mapping from image coordinates to OSGB coordinates.

**Comment by jacobbieker** [comment]
Will start on this once the big redesign #307 is merged!

**Comment by peterdudfield** [comment]
Whats the advantage of this? 

There is something nice, about just having it in one, and perhaps the satellite xr.Dataset loading both of them? Perhaps they are singificant different to suggest they should be in a different 'DataSource'

**Comment by jacobbieker** [comment]
The advantage is minimal code changes, the HRV dataset we can't add to teh non-HRV dataArray because of the different resolutions. And to cover the same area, the HRV cutout has to be 3x the size of the non-HRV image. Other than that, they would be the same, but the different size/shape of an HRV example vs non-HRV example suggests to me it might make sense to keep them as separate entries?

**Comment by JackKelly** [comment]
Yeah, I'd go with whatever is simplest to implement :)

**Comment by jacobbieker** [comment]
Cool, I'll do the HRV channel as a separate data source then!

**Comment by JackKelly** [comment]
Sounds good

Although, that said, I do agree with @peterdudfield that it feels kinda weird having two SatelliteDataSources... :slightly_smiling_face:   but let's give it a go and see how it feels!
