### ISSUE TITLE
Coordinates should be changed to `range(len(original_coords))` just before creating a batch

### ISSUE THREAD

**Issue by JackKelly** [openclimatefix/nowcasting_dataset#318]
## Detailed Description
Different DataSources do this slightly differently.  We should harmonise.  My proposal is that `make_dim_index` should be called as a final step in `get_batch()`.

For example, TopographicDataSource changes the coords in `get_example`.

And a few other little tweaks:

* Maybe remove `xr_utils.convert_data_array_to_dataset()` and instead call `to_dataset()` and `make_dim_index()` separately in calling code, so the calling code makes it clear when the index is being changed?
* Maybe rename `xr_utils.make_dim_index()`?
* Document where coords get changed.

**Comment by jacobbieker** [comment]
This cropped up again in #372 I found the same issue, which is causing some issues in the MetadataDataSource.
