### ISSUE TITLE
Standardise naming for `t0_datetime_UTC`, `x_center_OSGB`, `y_center_OSGB`

### ISSUE THREAD

**Issue by JackKelly** [openclimatefix/nowcasting_dataset#319]
* `DataSource.create_batches()` uses `t0_datetime_UTC`, `x_center_OSGB`, `y_center_OSGB` 
* `DataSource.get_batch()` uses `t0_datetimes`, `x_locations`, `y_locations`
* `DataSource.get_example()` uses `t0_dt`, `x_meters_center`, `y_meters_center`
* Other `DataSource` methods use other parameter names.

Also update docs in `data_sources/README.md`

I'm not entirely sure what's best but perhaps I'm leaning towards being verbose and using: `t0_datetime_UTC`, `x_center_OSGB`, `y_center_OSGB`, or something like that???  (Although do we _want_ different parameter names for singular objects (the single datetime fed into `get_example()` and plural (the `pd.DatetimeIndex` fed into `get_batch()`)

(This is my fault - I think these parameter names are from when I originally wrote `DataSource` months ago!)

**Comment by peterdudfield** [comment]
should it be 
- t0_datetime_utc
- x_center_osgb
- y_center_osgb?

**Comment by jacobbieker** [comment]
That sounds good to me

**Comment by JackKelly** [comment]
SGTM!
