### ISSUE TITLE
Use `Configuration` class to pre-process configuration objects (e.g. `Path(local_temp_path).expanduser()`)?

### ISSUE THREAD

**Issue by JackKelly** [openclimatefix/nowcasting_dataset#320]
The Pydantic `Configuration` model (in `nowcasting_dataset/config/model.py`) could perhaps be responsible for converting YAML configuration to the object that downstream-code uses... e.g. converting paths to `Path` or `Pathy` objects, and `expanduser()` where necessary?

**Comment by lenassero** [comment]
Hi Jack,

If I understand correctly, this could be done by adding a validator in `Process` for `local_temp_path` ? The same way as the [`filepath` validator in `OutputData`](https://github.com/openclimatefix/nowcasting_dataset/blob/7d5539a275a8bb64330d4bd7790a4bf1efa9f157/nowcasting_dataset/config/model.py#L309).

**Comment by JackKelly** [comment]
I think that's right!  @peterdudfield is the real expert on Pydantic though... what do you think of this plan, Peter?

**Comment by peterdudfield** [comment]
> Hi Jack,
> 
> If I understand correctly, this could be done by adding a validator in `Process` for `local_temp_path` ? The same way as the [`filepath` validator in `OutputData`](https://github.com/openclimatefix/nowcasting_dataset/blob/7d5539a275a8bb64330d4bd7790a4bf1efa9f157/nowcasting_dataset/config/model.py#L309).
> 
> Thanks !

I think thats a great idea, and a good way to do it

**Comment by lenassero** [comment]
Great, thank you both! I should handle that this week
