### ISSUE TITLE
Document new architecture (including a diagram)

### ISSUE THREAD

**Issue by JackKelly** [openclimatefix/nowcasting_dataset#324]
Once PR #307 is merged, add some documentation (to README.md?) to describe how `prepare_ml_data.py` works.

**Comment by peterdudfield** [comment]
Its describing how 'manger.py' works really, 

Ill try and put something together

**Comment by peterdudfield** [comment]
beginning it here - https://docs.google.com/presentation/d/10P0-EikNrJrGWzCrGEcXoktLTAwp8n7I-fwTT4IfNso/edit#slide=id.p

**Comment by peterdudfield** [comment]
![Screenshot 2021-11-10 at 10 26 43](https://user-images.githubusercontent.com/34686298/141096402-50f81a52-b15d-4adb-b1d7-361dfef77f65.png)
 something to start
