### ISSUE TITLE
Speed up `prepare_ml_data.py`

### ISSUE THREAD

**Issue by JackKelly** [openclimatefix/nowcasting_dataset#341]
## Detailed Description
After the "big new design", `prepare_ml_data.py` takes about 12 seconds per satellite batch.  That's too slow.  But, fear not, there are plenty of ways to speed it up!

After `prepare_ml_data.py` finishes with sun, topographic, and GSP (which all zoom past), `leonardo` really isn't being pushed very hard when it's only doing satellite and nwp:

![image](https://user-images.githubusercontent.com/460756/140508697-74024dbb-b268-40ea-8d9a-a1d80aa0915b.png)

## Possible Implementation
- [x] Write pre-prepared batches to `leonardo`'s new 4 TB SSD
- [x]  check that create batch is still using ThreadPoolExecutor to load examples in parallel 
- [x] #325 
- [x] #456
- [x] #311 
- [ ] #475 
- [ ] Use smaller dtypes for NWP and Satellite Zarrs (see #61).  Although satellite data is already 10-bit-per-channel, so reducing to 8-bit won't speed things up _that_ much.
- [ ] If needs be, bring back the idea of creating a batch by loading, say, 16 time slices off disk, and sampling 2 geographical regions of interest from each time slice to produce 32 examples per batch (i.e. halving the amount of data that needs to be loaded from disk per batch).  This definitely speeds up loading but reduces randomness.  This is how the code did it before "the big new redesign".... here's the commit where it was mostly removed: https://github.com/openclimatefix/nowcasting_dataset/pull/307/commits/f896a5e647d024a92505efcdf78ef957e2e6823a#L103 in `nwp_data_source.get_batch()`)
- [x] #305 
- [ ] #304  (but only bother with this if 305 is not sufficient)

**Comment by peterdudfield** [comment]
perhaps worth saying this is done for now?

**Comment by JackKelly** [comment]
yeah, good idea
