### ISSUE TITLE
Reduce duplication in `create_batches()` for Data Source and Manager

### ISSUE THREAD

**Issue by jacobbieker** [openclimatefix/nowcasting_dataset#367]
## Detailed Description
In the process of making #314 it came up that it is a bit difficult to extend the create_batches in DataSource for new types of data sources, like DerivedDataSource. As such, the code is quite similar and with decent parts of it nearly duplicated. So refactoring teh create_batches, and the `Manager.create_batches()` and `Manager.create_derived_batches()` could reduce code size quite a bit. 

## Context
Make it simpler code that is easier to maintain, and reduce duplication.

**Comment by lenassero** [comment]
Hi Jacob !

I can try to refactor the code in `data_source.py`. Shall I start from the `jacob/optical-flow-datasource` branch ?

Thanks

**Comment by jacobbieker** [comment]
Hi,

Yeah, if you want to make a branch off `jacob/optical-flow-datasource` to do the refactoring that would be fantastic! Thanks!

**Comment by lenassero** [comment]
Great, will do !

**Comment by JackKelly** [comment]
Hiya!  So, we've decided to remove the concept of a "DerivedDataSource" from the code, so this issue can be closed now, I think.    see https://github.com/openclimatefix/nowcasting_dataset/pull/314#issuecomment-982663427
