### ISSUE TITLE
Only use timesteps where Sun's elevation is > 10 degrees above horizon

### ISSUE THREAD

**Issue by JackKelly** [openclimatefix/nowcasting_dataset#373]
Throw away timesteps where, for a given geo region of interest, any geo location in that ROI has a Sun elevation <= 10 degrees.

**Comment by peterdudfield** [comment]
Im not sure this is critical - We can still train on data where <10, but just the outcome metrics shouldnt include these

**Comment by JackKelly** [comment]
Yeah, I agree it's not a total show stopper if we don't do this. But it will probably improve our ML performance if we ensure the train set has the same statistical properties as the test set. And this should be fairly easy to implement, I'd guess, because you've already done the hard work of computing the elevation :)

**Comment by peterdudfield** [comment]
I thought would easily be able to do this in [Sun.datetime_index](https://github.com/openclimatefix/nowcasting_dataset/blob/main/nowcasting_dataset/data_sources/sun/sun_data_source.py#L100)

But infact its a bit tricky as `Sun.elevation` is a dataframe of time vs (x,y)-location. This means the datetimes are the location dependent, but that goes a bit against our manager.py [workflow](https://github.com/openclimatefix/nowcasting_dataset/blob/main/nowcasting_dataset/manager.png) - as 'get locations' is from just one 'data_source'

Perhaps there is an easier way ....

Next step: 
plot elevations throughout the year across the UK - for understanding of things

**Comment by peterdudfield** [comment]
![Screenshot 2021-11-17 at 08 49 18](https://user-images.githubusercontent.com/34686298/142167734-97992e03-388a-45c7-99ed-d648518143ba.png)

**Comment by peterdudfield** [comment]
![Screenshot 2021-11-17 at 08 55 23](https://user-images.githubusercontent.com/34686298/142168968-73d03449-4371-4c62-a05a-81eddb3e70d9.png)
![Screenshot 2021-11-17 at 08 56 13](https://user-images.githubusercontent.com/34686298/142168972-ff666968-092f-45f1-a005-ac12e44daf2c.png)
![Screenshot 2021-11-17 at 08 56 36](https://user-images.githubusercontent.com/34686298/142168975-02661c77-f099-4f53-a693-2f35cc1404e7.png)
![Screenshot 2021-11-17 at 08 56 56](https://user-images.githubusercontent.com/34686298/142168979-06cc8d68-dff5-4004-9903-2bb2f0c136bc.png)

**Comment by peterdudfield** [comment]
So potentially we just remove anytimes stamps  where elevation <10 for Shetlands - this means we might lose some data where the elevation is >10 int he south but not in the north, 

We will only really loss timestamps in winter though

**Comment by peterdudfield** [comment]
Another way could be to edit `[select_daylight_datetimes](https://github.com/openclimatefix/nowcasting_dataset/blob/main/nowcasting_dataset/time.py#L20)` to select elevation > 10

**Comment by peterdudfield** [comment]
Perhaps the easiest to do is, only select datetimes where 'london' > 10 for training, and then in the evaluations metrics we are a lot stricter with the filtering.

**Comment by JackKelly** [comment]
> Perhaps the easiest to do is, only select datetimes where 'london' > 10

Yeah, I agree, let's just use that criterion for now!  Simple is good :slightly_smiling_face: (simple is good for our code; and simple is good in terms of _explaining_ our code to ESO!)  TBH, I would guess the "London" criterion is probably OK for testing too (at least, for WP1), because most of Britain's PV capacity is in the South.  What do you think, @peterdudfield & @jacobbieker?

Then, in early 2022, as you say, we can think about how to re-architect `Manager` so that, when it generates the list of locations for each example, it takes into consideration the issue you've raised above:  that the Sun's elevation is dependent on the location and the datetime.

How does that sound?

**Comment by JackKelly** [comment]
We should ask Dan too... I'll add this issue to today's "OCF Sync" meeting so we can get Dan's opinion...

**Comment by peterdudfield** [comment]
> Great plots!
> 
> > Perhaps the easiest to do is, only select datetimes where 'london' > 10
> 
> Yeah, I agree, let's just use that criterion for now! Simple is good 🙂 (simple is good for our code; and simple is good in terms of _explaining_ our code to ESO!) TBH, I would guess the "London" criterion is probably OK for testing too (at least, for WP1), because most of Britain's PV capacity is in the South. What do you think, @peterdudfield & @jacobbieker?
> 
> Then, in early 2022, as you say, we can think about how to re-architect `Manager` so that, when it generates the list of locations for each example, it takes into consideration the issue you've raised above: that the Sun's elevation is dependent on the location and the datetime.
> 
> How does that sound?

I think thats very sensible

**Comment by JackKelly** [comment]
> Then, in early 2022, as you say, we can think about how to re-architect Manager

Here's a new issue to remind us to do this re-architecting in 2022: #421

**Comment by jacobbieker** [comment]
Yeah, I think that sounds good too!

**Comment by JackKelly** [comment]
This will be fixed when PR #417 is merged
