### ISSUE TITLE
Remove unused consts

### ISSUE THREAD

**Issue by JackKelly** [openclimatefix/nowcasting_dataset#386]
Possibly remove these from `consts.py` and `grep -r --include=*.py` through the code to find other uses of these consts:

* BUCKET
* SAT_FILENAME
* PV_PATH
* PV_FILENAME
* PV_METADATA_FILENAME
* NWP_FILENAME

**Comment by lenassero** [comment]
Hi Jack!

I could tackle this little first issue !

For the mentioned variables:
- `BUCKET`, `PV_PATH` an `PV_FILENAME` and `PV_METADATA_FILENAME` are not imported anywhere inside `nowcasting_dataset`(they are usually redefined in the different notebooks or scripts) 
- `NWP_FILENAME` is never used either
- `SAT_FILENAME` however seems to be used in two places: [here](https://github.com/openclimatefix/nowcasting_dataset/blob/8e85735dbd26dbd517b4bf2b3495de1d3e99b8a5/conftest.py#L34) and [here](https://github.com/openclimatefix/nowcasting_dataset/blob/8e85735dbd26dbd517b4bf2b3495de1d3e99b8a5/scripts/generate_data_for_tests/generate_satellite_test_data.py#L22)

**Comment by JackKelly** [comment]
Great work!  Thanks so much for diving in!

Please do go ahead and delete `BUCKET`, `PV_PATH`, `PV_FILENAME`, `PV_METADATA_FILENAME`, and `NWP_FILENAME`!

And maybe we should create a new issue specifically to remove `SAT_FILENAME`.

**Comment by peterdudfield** [comment]
Thanks @lenassero for this work - ill keep this issue open until a new issue is made for `SAT_FILENAME`

**Comment by peterdudfield** [comment]
@all-contributors please add @lenassero for code
