### ISSUE TITLE
New Satellite data results in non-square cutouts

### ISSUE THREAD

**Issue by jacobbieker** [openclimatefix/nowcasting_dataset#401]
**Describe the bug**
The new satellite data is not reprojected to a square grid, and is in the original projection. This means, though, that the pixels are non-uniform distances apart in the real world. This manifests itself with the new format specifically when trying to make examples:

When doing slices on the new satellite data, using the HRV Zarr, each pixel in the x direction seems to be between ~1200 and 1100 meters from each other, and in the y-direction between ~3200 and 2200 meters, leading to very non-square ouputs when slicing along them. For non-HRV, its roughly 3400m on average across x, and 7100 for y. So this ends up with very rectangular outputs.

**To Reproduce**
1. Go to `jacob/satellite-zarr` branch
2. Run any of the satellite tests or `test_manager.py:test_batches()`

**Expected behavior**
Square cutouts to be made, or at least cutouts to work.

**Additional context**
Not sure the best way of fixing this, could be through resampling to a square grid for the cutout area? But that removes the point of not reprojecting the data. Since inputs do not have to be square, could just have rectangular outputs.

**Comment by JackKelly** [comment]
Ooh, interesting!

Yeah, I think it's fine to give the model satellite cutouts that are square in the number of _pixels_ (e.g. 64 x 64 _pixels_), even though that represents a warped rectangle in the real world.

Maybe, for now at least, we'll make the user responsible for manually configuring `image_size_pixels` for each `DataSource` such that each DataSource's region of interest roughly overlaps in the real world?  (e.g. so the NWP and satellite data overlaps in the real world)?

**Comment by jacobbieker** [comment]
Okay, yeah, that's what I was thinking, adding in rectangular cutouts makes it a lot more difficult, and doesn't quite make sure every satellite example is the same size anyway. I'll, for now, just have it interpolate to a square grid of the right size after it slices along the x and y dimensions. The position encoding should still then help the model know where each of those pixels are in real space.

**Comment by JackKelly** [comment]
> I'll, for now, just have it interpolate to a square grid of the right size after it slices along the x and y dimensions.

Sorry, I'm being slow... why do we need to interpolate?  :slightly_smiling_face: 

If the satellite cutout is square in pixel space (e.g. 64 x 64 pixels), isn't that all that matters?

**Comment by jacobbieker** [comment]
Ah okay, yeah, nevermind. I was thinking after the line below, which makes a rectangular cutout in pixel space, you were saying then map that to a square grid. 

```
 selected_data = selected_data.sel(
            x=slice(bounding_box.left, bounding_box.right),
            y=slice(bounding_box.top, bounding_box.bottom),
            )
```

Yeah, I can make it just make a square cutout, it'll result in 'real' spatial terms, the cutout  covering twice as much distance in the x direction as the y direction, but yeah, then no interpolation is needed.

**Comment by JackKelly** [comment]
> it'll result in 'real' spatial terms, the cutout covering twice as much distance in the x direction as the y direction

For now at least, I think that's fine (and might actually be _good_ because, at least for the UK, the dominant wind direction is from the west :slightly_smiling_face: )

**Comment by jacobbieker** [comment]
Closing for now, the code makes square cutouts and seems to work!
