### ISSUE TITLE
Compute means and standard deviation for new NWP Zarr

### ISSUE THREAD

**Issue by JackKelly** [openclimatefix/nowcasting_dataset#407]
Not super-urgent, because out config files ensure that we're still using the same variables as before, which _should_ have the same mean and std!  But we'll def have to compute means and stds for the new vars, if we want to use the new vars!

See #43 for some notes about using dask to compute means.

**Comment by peterdudfield** [comment]
@jacobbieker did this get done?

**Comment by jacobbieker** [comment]
Yes

**Comment by JackKelly** [comment]
I think we probably need to re-do this with the new NWP zarr. The old zarr jumbled up the channels

**Comment by peterdudfield** [comment]
did this get done? https://github.com/openclimatefix/nowcasting_dataloader/pull/81

**Comment by JackKelly** [comment]
So, that PR computed the normalisation stats from the training batches, rather than the Zarr.  But, given that, going forwards, I'm pretty confident that we should always compute the normalisation stats from the training batch, we can mark this as closed for now.
