### ISSUE TITLE
strange Sun location

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting_dataset#416]
**Describe the bug**
One sun location systems is at 
lat lon: 30,102

This is not in the UK

**To Reproduce**
Run 
```
zarr_path='tests/data/sun/test.zarr'
    sun_data_source = SunDataSource(zarr_path=zarr_path, history_minutes=30, forecast_minutes=60)
print(sun_data_source.elevation.iloc[:,382:384]
```

**Expected behavior**
locations systems to be in the UK

**Comment by JackKelly** [comment]
Good catch!

Hopefully the code will already ignore any PV systems that are outside of the UK (because the PV system won't be in the region of interest)?

**Comment by JackKelly** [comment]
Um, just to check:  _does_ PR #417 fix this issue with strange Sun locations?

**Comment by peterdudfield** [comment]
This will - https://github.com/openclimatefix/nowcasting_dataset/pull/419
but waiting on https://github.com/openclimatefix/nowcasting_dataset/pull/339 first

**Comment by peterdudfield** [comment]
No longer an issue

```
from nowcasting_dataset.geospatial import osgb_to_lat_lon
from nowcasting_dataset.data_sources.sun.sun_data_source import SunDataSource

zarr_path='tests/data/sun/test.zarr'
sun_data_source = SunDataSource(zarr_path=zarr_path, history_minutes=30, forecast_minutes=60)
print(sun_data_source.elevation.iloc[:,382:384])

locations = [col.split(',') for col in sun_data_source.elevation.columns]
x = [float(l[0]) for l in locations]
y = [float(l[1]) for l in locations]
lat, lon = osgb_to_lat_lon(x,y)

print(max(lat), min(lat))
print(max(lon), min(lon))

60.2 50.0
1.75 -6.91
```

No longer a problem
