### ISSUE TITLE
GSP xr.dataset has 'data' --> 'power_mw'

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting_dataset#447]
## Detailed Description
Batch data has 'data' as a data var and it should be called power_mw

**Comment by peterdudfield** [comment]
https://github.com/openclimatefix/nowcasting_dataset/blob/main/nowcasting_dataset/data_sources/gsp/gsp_model.py#L15
shows it should be 'power_mw'

**Comment by peterdudfield** [comment]
Moving this up to critical as I think this should be done before new batches are made

**Comment by JackKelly** [comment]
I've added this to the list in issue #393 :slightly_smiling_face:
