### ISSUE TITLE
Do the GSP batches include the GSP name?  If so, please can we add GSP name to the GSP batches?

### ISSUE THREAD

**Issue by JackKelly** [openclimatefix/nowcasting_dataset#451]
## Detailed Description
So our ML models can use an embedding of the GSP name.

**Comment by jacobbieker** [comment]
Does the ID count? The GSP ID is included in the batches

**Comment by peterdudfield** [comment]
Id is in there

**Comment by JackKelly** [comment]
Lovely, thanks guys!  (Sorry for being too lazy to check the code!  I wanted to remind myself that this is important before I forgot!)
