### ISSUE TITLE
allow `prepare_ml_data.py` to run without GSP data source after locations CSV files have been created

### ISSUE THREAD

**Issue by JackKelly** [openclimatefix/nowcasting_dataset#457]
## Detailed Description
GSP data source is required to sample geo locations from.  But, once the locations CSV files have been created, it should be possible to run `prepare_ml_data.py` with any subset of DataSources (e.g. just 'satellite').

But, if gsp isn't included, then prepare_ml_data.py complains because it always checks whether the data source that defines the geospatial regions is in the list of datasources.

We should re-order the code a little so that the code is happy with any subset of DataSources (after the CSV files specifying the locations have been created)

**Comment by peterdudfield** [comment]
I just got this, 
got round it by using
```python scripts/prepare_ml_data.py --data_source=gsp --data_source=pv``` 
for the moment

**Comment by JackKelly** [comment]
PR #492 fixes this issue
