### ISSUE TITLE
GSP centroid not in the center

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting_dataset#463]
## Detailed Description
looking at batch

![Screenshot 2021-11-18 at 15 37 12](https://user-images.githubusercontent.com/34686298/142446779-b66a2e20-3b61-4189-b8e1-9225fe55f29d.png)

## Context
Good to have GSP at the middle, so we gather information around it

**Comment by JackKelly** [comment]
Good catch!

**Comment by peterdudfield** [comment]
![Screenshot 2021-11-18 at 15 45 54](https://user-images.githubusercontent.com/34686298/142448323-3bbf9ffc-c831-4f1e-8455-e6c63c343ec7.png)
 some are though

**Comment by JackKelly** [comment]
Please could you explain what the plots mean?

**Comment by peterdudfield** [comment]
AH sorry, yea I didn't copy the key. 

Plots of GSP batch, with the first GSP coords being the centre one (BLUE)

**Comment by JackKelly** [comment]
> Got it

Nice!

> Plots of GSP batch, with the first GSP coords being the centre one (BLUE)

Nice.  And, for fear of asking a dumb question, what do the green circles represent?

**Comment by peterdudfield** [comment]
oh, itll be GSP power intensity - I got a TODO to upgrade it to a shape

**Comment by peterdudfield** [comment]
![Screenshot 2021-11-18 at 17 09 54](https://user-images.githubusercontent.com/34686298/142463281-4650d611-71e1-4a9b-a237-926d441571ae.png)
