### ISSUE TITLE
`satellite.log` file is not being appended to

### ISSUE THREAD

**Issue by JackKelly** [openclimatefix/nowcasting_dataset#467]
Need to fix `Manager.configure_loggers()`

**Comment by JackKelly** [comment]
I think the satellite logger is `nowcasting_dataset.data_sources.data_source:SatelliteDataSource` whilst GSP is like `nowcasting_dataset.data_sources.gsp...`

**Comment by peterdudfield** [comment]
Is this a specific satellite log not being attending to, or is it all logs?

**Comment by peterdudfield** [comment]
https://github.com/openclimatefix/nowcasting_dataset/runs/4407519504?check_suite_focus=true

Interestingly the test only failed on Mac, but not on Ubuntu

**Comment by JackKelly** [comment]
> Is this a specific satellite log not being appended too, or is it all logs?

so, it's specifically `/mnt/storage_ssd_4tb/data/ocf/solar_pv_nowcasting/nowcasting_dataset_pipeline/prepared_ML_training_data/v15/satellite.log` that doesn't seem to get updated properly

I've made a few fixes of the logging code in the OpticalFlow PR, but I haven't tried running the satellite data source yet.

there's some more helpful thoughts about what the problem might be in comments in `Manager.configure_loggers()`

**Comment by peterdudfield** [comment]
I think this fixed it
![Screenshot 2021-12-03 at 10 26 57](https://user-images.githubusercontent.com/34686298/144600347-dec6434e-b26e-43c4-b365-2c99ce7f4c63.png)
