### ISSUE TITLE
Run `prepare_ml_data.py` this weekend

### ISSUE THREAD

**Issue by JackKelly** [openclimatefix/nowcasting_dataset#471]
For the satellite data source, it looks like it takes about 8 seconds per batch.  So that's about 2.3 days for 25,000 batches.

Before running `prepare_ml_data.py` for the weekend, pls make sure `/mnt/storage_ssd_4tb` has enough space!

(BTW, if you want to run `prepare_ml_data.py` to create a single DataSource (after first creating the CSV files defining the position of every example) then, for now, you must always include `gsp`... that'll be fixed in #457)

**Comment by peterdudfield** [comment]
batches are made to train=4000, test=400. Maybe we could leave this

**Comment by JackKelly** [comment]
Yeah, let's close this for now!  We'll have to re-run `prepare_ml_data.py` when the NaNs and -1s are fixed, though :slightly_smiling_face:
