### ISSUE TITLE
Nans in NWP

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting_dataset#481]
**Describe the bug**
There are Nans in the NWP data

**To Reproduce**
Open mnt/storage_ssd_4tb/data/ocf/solar_pv_nowcasting/nowcasting_dataset_pipeline/prepared_ML_training_data/v14/train/nwp/000000.nc and have a look

**Expected behavior**
no nans

**Comment by JackKelly** [comment]
As discussed this morning, I'll look into this issue today...

**Comment by JackKelly** [comment]
In `v14/train/nwp/000000.nc` all the NaNs are in `channels_index=5`.  So, a very quick hack fix would be to ignore `channels_index=5`.  I'll do a more thorough check now, and change the nowcasting_dataset code...

![image](https://user-images.githubusercontent.com/460756/142876835-47823d38-0dbe-470b-a533-2cd61236ed13.png)

**Comment by JackKelly** [comment]
That bad data looks like it's coming from the `hcct` channel (Height of convective cloud top) which, by design, has NaNs where there are no clouds, I think.  BUT, this suggests another bug:  The YAML config doesn't request the `hcct` channel!

**Comment by JackKelly** [comment]
Hmm... as far as I can tell, the code is correctly loading the list of NWP channels requested by the YAML config.  And so `hcct` _shouldn't_ be in the batches... I'll keep digging!...  

The PR for this fix is #492

**Comment by JackKelly** [comment]
next step:  Log _where_ the NaNs are.

**Comment by JackKelly** [comment]
aha!  The problem is in the intermediate Zarr:  Sometimes the channel labelled "si10" (10 meter wind speed) has data from the `hcct` channel in it!

**Comment by JackKelly** [comment]
Yeah, it did take me awhile!  But, in retrospect, I really should have started with the intermediate Zarr!

**Comment by JackKelly** [comment]
OK, the new intermediate Zarr is finished (although it only covers 2020 and 2021) and I'm recreating the NWP batches from batch 0.  It's doing about 2 NWP batches per second.  So far, there have been no log messages about NaNs :slightly_smiling_face:
