### ISSUE TITLE
-1s in the satellite data

### ISSUE THREAD

**Issue by JackKelly** [openclimatefix/nowcasting_dataset#484]
I'll look into this ~~later today~~ on Tuesday

**Comment by JackKelly** [comment]
I'll look into this now...

**Comment by JackKelly** [comment]
it looks like none of the HRV Zarr data has -1s... I'm checking the other channels now..

**Comment by JackKelly** [comment]
`v2/eumetsat_zarr_2020_02.zarr` has (at least one) `-1`.

As far as I can tell, all the other satellite Zarrs are fine

I'll dig into `v2/eumetsat_zarr_2020_02.zarr` to find out where the `-1`s are...

**Comment by JackKelly** [comment]
FWIW, `dask` was being a bit weird when using `xr.open_mfdataset` so here's the code I eventually settled on to find `-1`s:

```python
import xarray as xr
import glob
import dask.array

ZARR_PATH = "/mnt/storage_ssd_8tb/data/ocf/solar_pv_nowcasting/nowcasting_dataset_pipeline/satellite/EUMETSAT/SEVIRI_RSS/zarr/v2/hrv_eumetsat_*.zarr"
filenames = glob.glob(ZARR_PATH)
for filename in filenames:
    print(filename, flush=True)
    with xr.open_dataset(filename, mode="r", engine="zarr", chunks='auto') as ds_from_zarr:
        if dask.array.isclose(ds_from_zarr['stacked_eumetsat_data'], -1).any().compute():
            print(filename, "has -1!!!", flush=True)
        else:
            print(filename, "is fine", flush=True)
    print()
```

**Comment by JackKelly** [comment]
Yup, there's definitely some bad data in `v2/eumetsat_zarr_2020_02.zarr` :slightly_smiling_face: 

![image](https://user-images.githubusercontent.com/460756/143049359-3de69cd7-4490-495b-8c6b-a34bc85b6b00.png)

I'll keep digging..

**Comment by JackKelly** [comment]
Every timestep and every channel I've looked at in `v2/eumetsat_zarr_2020_02.zarr` looks similar to the plot above (i.e. looks like noise!  With some weird white lines.  And the values range from -30,000 to 30,000!

I think the fix is probably quite simple:  We just delete `v2/eumetsat_zarr_2020_02.zarr`.  What do you think, @jacobbieker?

**Comment by jacobbieker** [comment]
Yeah, that sounds good!

**Comment by JackKelly** [comment]
OK!  I'll delete `v2/eumetsat_zarr_2020_02.zarr` now!
