### ISSUE TITLE
Missing NWP data

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting_dataset#494]
## Detailed Description
In ':/mnt/storage_ssd_4tb/data/ocf/solar_pv_nowcasting/nowcasting_dataset_pipeline/prepared_ML_training_data/v14/train/nwp'
there are only 769 batches. Should be 4000
non in the test folder

## Context
need this to run ML models

## Possible Implementation
run preapre_ml_script.py - but might be after https://github.com/openclimatefix/nwp/issues/6

**Comment by JackKelly** [comment]
yeah, please wait for nwp#6 before re-creating nwp batches

creating nwp batches should be a lot faster after my latest pr is merged

**Comment by JackKelly** [comment]
I'm gonna close this for now... we (hopefully) just need to re-run `prepare_ml_data.py --data_source nwp` after the new NWP Zarr is created (and we'll need to update the config to use the new NWP zarr)

**Comment by JackKelly** [comment]
We now have a full set of NWP batches
