### ISSUE TITLE
Create new batches from scratch 

### ISSUE THREAD

**Issue by JackKelly** [openclimatefix/nowcasting_dataset#496]
After #495 is done.

We need to create again from scratch because we've removed a month of satellite data

**Comment by JackKelly** [comment]
creating new batches in v15 on leonardo now...

**Comment by JackKelly** [comment]
`prepare_ml_data.py` has finished making `train` batches for all DataSources except `hrvsatellite`... it should be completely done in a few hours...

**Comment by peterdudfield** [comment]
All your speed ups have helped - well done
