### ISSUE TITLE
Upload data to the cloud?

### ISSUE THREAD

**Issue by JackKelly** [openclimatefix/nowcasting_dataset#498]
(After #496 is done)

v14 is only 183 GBytes.  So we could upload v15 to the cloud, so folks can be running experiments without waiting for `leonardo` to be ready :slightly_smiling_face:

**Comment by JackKelly** [comment]
`pbzip2` reduces the file size of the NWP batches from 21 MB to 3.8 MB (!) (i.e. reduces it to 20% of its original size).  Assuming the same compression ratio is possible across all the data, the entire pre-prepared dataset should be only 40 GBytes compressed (so, totally fine for uploading to the cloud!)

**Comment by JackKelly** [comment]
`prepare_ml_data.py` has finished creating the new `train` set.

So I've set `pbzip2` compressing all the `train` batches.

We have no free credits on GCP right now.  Would it be useful to upload to AWS?  I think we still have free credits on AWS.  Is that right, @flowirtz?

Also, @jacobbieker, feel free to download the compressed batches to your laptop if that's useful :slightly_smiling_face:

**Comment by peterdudfield** [comment]
Yea copying them up to AWS I think would be a good idea

**Comment by peterdudfield** [comment]
Ive been copying them to here - s3://solar-pv-nowcasting-data/prepared_ML_training_data/v15_compressed/

and unzipping them to s3://solar-pv-nowcasting-data/prepared_ML_training_data/v15

Still in progress
