### ISSUE TITLE
Investigate why 0 data for some GSP

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting_dataset#518]
## Detailed Description
Some GSPs have zero data in the v15 tests
see https://github.com/openclimatefix/nowcasting_utils/issues/66 for disturbution plot

**Comment by peterdudfield** [comment]
the missing gsp ids are [18, 25, 34, 41, 47, 50, 76, 89, 112, 114, 160, 164, 175, 180, 185, 203, 206, 215, 217, 222, 258, 260, 270, 278, 313, 314, 316, 317, 318, 331, 333]

now to plot them

**Comment by peterdudfield** [comment]
![Screenshot 2021-12-03 at 15 47 38](https://user-images.githubusercontent.com/34686298/144631333-6d937efa-79c9-48d8-93f1-b5f773c503ef.png)

**Comment by peterdudfield** [comment]
This can be divded into two groups

GSP data with nans in it and no nans
Nans:  [18, 25, 34, 41, 47, 50, 76, 89, 112, 114, 185, 203, 215, 222, 258, 260, 270, 278, 313, 314, 316, 317, 318, 331, 333]
No Nans: [160, 164, 175, 180, 206, 217]

lets plot the no nans ones - they are all in scoatland
![Screenshot 2021-12-03 at 16 03 16](https://user-images.githubusercontent.com/34686298/144633795-ba41e3fa-390c-4b35-a8c0-04b71e925f55.png)

**Comment by peterdudfield** [comment]
164, 175, 180, 206, has a maximum of 0. 
160, 217 are passed 1_036_975 (OSGB) in the y coords, and are therefore filter out.

So we are left with why are these gsp go nans in them
[18, 25, 34, 41, 47, 50, 76, 89, 112, 114, 185, 203, 215, 222, 258, 260, 270, 278, 313, 314, 316, 317, 318, 331, 333]

**Comment by peterdudfield** [comment]
For 
[18, 25, 34, 41, 47, 50, 76, 89, 112, 114, 185, 203, 215, 222, 258, 260, 270, 278, 313, 314, 316, 317, 318, 331, 333]

looking at one day "2020-07-01" they all have zero PV values. This is directly from PV live

**Comment by peterdudfield** [comment]
Ill close this for moment, as all empty GSP have been explained

**Comment by JackKelly** [comment]
> Ill close this for moment, as all empty GSP have been explained

Just to check I understand:  Is the explanation that the "missing" GSPs have zero installed PV capacity?
