### ISSUE TITLE
Azimuth & angle of Sun

### ISSUE THREAD

**Issue by JackKelly** [openclimatefix/nowcasting_dataset#52]

**Comment by peterdudfield** [comment]
Started looking at this on branch 'issue/52-sun-angle'
https://github.com/openclimatefix/nowcasting_dataset/tree/issue/52-sun-angle

**Comment by JackKelly** [comment]
Thanks so much for diving into the `nowcasting_dataset` code and working on some of the issues!  Absolutely awesome work!  (Sorry the code is a bit of a mess!)  I've got a few vaguely urgent emails to reply to this morning but I'll try to look at your pull requests before we chat this afternoon :)

**Comment by peterdudfield** [comment]
https://github.com/openclimatefix/nowcasting_dataset/pull/70

@JackKelly no rush on this, just something I'm ticking away with

**Comment by peterdudfield** [comment]
code in there, next step is to add it to the prepared ML data set

**Comment by peterdudfield** [comment]
To get all the Azimuth angles, for time of day and locations, it took an hour. Perhaps a good way would be to do this process in one step first and save the dataset, and then load it later. 

My feeling also is there must be a simple formula  that we can run on to calculate these.

**Comment by JackKelly** [comment]
> Perhaps a good way would be to do this process in one step first and save the dataset, and then load it later.

That sounds like a good idea to me!  And maybe that pre-prepared dataset of Azimuth angles could extend a little way into the future (say, to the end of 2022), so we don't have to worry about re-computing the Azimuth angles for a while?

**Comment by peterdudfield** [comment]
Needs to be {locations} x {time} vector, so perhaps I can do ~1km2 square grids in 5 min timesteps,  and then have a method to interpolate these for the actual location of the pv system

**Comment by JackKelly** [comment]
That could work!

For now, would it be simpler to pre-compute the Azimuth & angle of the Sun _just_ for each PV system, and for the centroid of each GSP region?  (Instead of doing it at 1km^2 square grids)?  Or have I missed something?!  :)

**Comment by peterdudfield** [comment]
It would be simplier, but when a new one gets added, we need to be able to run it for the new one. Perhas thats the way to do it, have a scrip that can eaily append new locations (and times)

**Comment by JackKelly** [comment]
sounds good to me! :)

**Comment by peterdudfield** [comment]
I think i'll split into a separate datasource (out of pv data source), so its more general, and can be loaded nicely

**Comment by peterdudfield** [comment]
Currently one year of data is ~ 250 MB. This is about ~2000 sites for 365*288 timestamps = 100 million data points. 
My thinking is that 1 year will be enough accuracy for us to use for all the years, but I will look into the differences in the data in the differenent years

**Comment by JackKelly** [comment]
Sounds good to me!

@jacobbieker, as our resident astrophysicist :), are we safe to assume that the azimuth and angle of the sun will always be the same for a given time-of-year?  (I assume so, but I know just enough physics to know that I really don't understand very much physics!)

**Comment by jacobbieker** [comment]
I think technically no, it changes, as the Earth wobbles around its axis over time, but that is only noticeable over the course of  thousands or hundreds of thousands of years, so it should be a very good approximation for the next few thousand years or so ;) So in essence, yeah that should be a fine thing to assume.

**Comment by JackKelly** [comment]
@peterdudfield now that #70 is merged, I'll close this issue.  Please re-open if I've misunderstood!
