### ISSUE TITLE
Include summary stats for PV power (to capture info when there's > 128 PV systems in ROI)

### ISSUE THREAD

**Issue by JackKelly** [openclimatefix/nowcasting_dataset#539]
## Detailed Description
Our batches only store up to 128 PV systems per example.  But sometimes there are more PV systems available.  At the moment, those systems get lost.  But maybe we should always compute some summary stats (mean, std, min, max?) across all PV systems, and store those stats, so our models can always benefit at least a bit from all the PV systems in the region of interest.

**Comment by peterdudfield** [comment]
Yea the summary statistics are probably useful. 

I was thinking we could even sort the PV systems in order of closest to the GSP center. This means the first few PV systems will be more correlated. This way we could select the highest correlated PV systems. 

One idea might be to save 10% for random PV systems, as PV systems outside the GSP regions are clear useful when predicting the future GSP i.e if a cloud is coming.

**Comment by jacobbieker** [comment]
Would we want to summarize only the PV systems in the GSP? Since that should correlate more with the GSP output?

**Comment by JackKelly** [comment]
> sort the PV systems in order of closest to the GSP center

that's a good idea!

> Would we want to summarize only the PV systems in the GSP? Since that should correlate more with the GSP output?

Good point... 

But, in 2022, I'm really excited about us trying to train models which can associate clouds in the last ~hour of satellite imagery with PV power (for example, to infer "that big dark cloud caused a 76% drop a power generation an hour ago, and the cloud is heading this way, so maybe it'll cause a 76% drop when in hits my GSP an hour from now").  Which is to say that it will hopefully be useful to include PV power from a wide geographical extent.  (to build on the work you've already done, Jacob, to predict satellite imagery, and add in PV..., or something like that... :slightly_smiling_face: )

TBH, the PV data is so small that I wonder if we should just set an upper limit so high that we never have to drop PV systems from a batch?  That might be the simplest solution?  (Although it might also be nice to sort the PV systems in each example, like Peter suggested, so that smaller ML models can just pick the first, say, 32 PV systems... but larger experiments can take all 1,300 PV systems we wanted!

**Comment by jacobbieker** [comment]
Yeah, I would be for not dropping any PV systems from a batch, and since the data is so small, potentially including PV systems further afield than the imagery extant? If the model can learn to place the PV system in space correctly, and it notices that some PV systems outside the imagery is losing power, it could also maybe infer that a cloud is coming and will be coming into the satellite imagery soon

**Comment by JackKelly** [comment]
yeah, good idea, maybe we could keep things simple and just always include all ~1,300 PassivSystem PV systems?!  (Possibly sorted by proximity to the center of the GSP region).

**Comment by JackKelly** [comment]
(TBH, my hunch from the last couple of weeks of ML experiments is that the lowest hanging fruit for improving our PV nowcasts further might be to extract as much info as we can from the recent history of PV data... so including all 1,300 PV systems - or a sizable subset - could be a quick win)

**Comment by peterdudfield** [comment]
Yea i agree, including would be great. 

Different issue could be to order them, so that the closes ones are at the top. That would help out the simplier modesl that dont get given coordinates

Ill make a v17 dataset milestone where we can put a few things in. Probably only complete it in the new year though
