### ISSUE TITLE
Log configuration of each data source

### ISSUE THREAD

**Issue by JackKelly** [openclimatefix/nowcasting_dataset#541]
## Detailed Description
To help us debug things, it'd be great if each DataSource logged its full config when it starts up (e.g. its `image_size_pixels`, `history_minutes`, etc.)

## Context
Helpful for debugging

**Comment by peterdudfield** [comment]
thats a good one
Perhaps it go in [here](https://github.com/openclimatefix/nowcasting_dataset/blob/main/nowcasting_dataset/manager.py#L117) although this will go in the general logger. 

If we want something in the data source specific logs then we need to add it to the data source specific file
