### ISSUE TITLE
Not enought GSP in batch

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting_dataset#542]
## Detailed Description
Default of 32 GSP for each batch is not enough
![Screenshot 2021-12-13 at 15 27 46](https://user-images.githubusercontent.com/34686298/145840116-7f8acc7b-aad7-4d71-9744-e245903bb8ab.png)

not all GSP are given. 

## Context
Useful to give GSP closest information

## Possible Implementation
- increase GSP size
- only select closest GSPs to center

**Comment by JackKelly** [comment]
Please can you give some more context?  I'm not sure I understand exactly what the issue is?

Surely we only need one GSP per example?  (the target GSP).  

What's the issue with having only 32 GSPs per batch?  (i.e. exactly one GSP per example)?

**Comment by peterdudfield** [comment]
Yea i think I have confused myself. Currently there are 32 GSPs in batch. This is when we thought we could use the GSP data in the predictions. 

1. So one way forward is to just remove the GSP data, apart from the one we are trying to predict
2. check for PV systems, could also be the same problem and we need to make sure. We could perhaps pick the closes PV systesm to the GSP centroid, so the ML can pick the more correlated ones more easily

**Comment by peterdudfield** [comment]
Im going to close this, as this is not useful and somewhat confusing
