### ISSUE TITLE
Add "condensed_2_minutely_pv_system_id" to PV batches

### ISSUE THREAD

**Issue by JackKelly** [openclimatefix/nowcasting_dataset#552]
## Detailed Description
The PassivSystems PV system IDs exist in the range [1, 25,000ish].  But we only use data from about 1,300ish of those PV systems.

As well as the raw PV system ID, it would be good to include a "condensed" PV system ID, in the range [0, 1300].  i.e. every integer between 0 and 1,300 would be assigned to a PV system we actually use.

(This isn't super-important because it only takes about a millisecond to compute this on the fly for each batch).

## Context
When using a [`torch.nn.Embedding`](https://pytorch.org/docs/stable/generated/torch.nn.Embedding.html), we have to specify the vocabulary size up-front.  It's super-inefficient to specify a vocab size of 25,000 when, actually, we only use 1,300 PV systems.  It's far more efficient to use a vocab size of 1,300.

## Possible Implementation
It takes less than a millisecond to map PV system IDs to a "condensed" ID, if using a look up table... there's a scruffy example of how to do this in [my ML experiments notebook](https://github.com/openclimatefix/predict_pv_yield/blob/jack/ML-experiments/notebooks/51.30_optical_flow_predictions_into_perceiver.ipynb) (especially the `get_pv_system_id_index_lut()` function)

**Comment by peterdudfield** [comment]
could do this as part of #554

**Comment by peterdudfield** [comment]
Does 'pv_system_row_number' not do this? 
pv_system_row_number is a list of number from 0 to 'total_pv_systems' . The list of number represents the pv system in that example.
