### ISSUE TITLE
Modify `satellite_data_source` to handle 2D x_osgb and y_osgb coords

### ISSUE THREAD

**Issue by JackKelly** [openclimatefix/nowcasting_dataset#576]
## Detailed Description
In the newly updated Zarrs, the `x_osgb` and `y_osgb` coordinates are a little different to the old Zarrs (these differences were necessary to fix the incorrect OSGB coordinates):

* In the new Zarrs, `x_osgb` and `y_osgb` are both 2D matrices
* In the new Zarrs, the 'main' coords are the geostationary coords `x` and `y`.

`nowcasting_dataset` needs to be modified so it knows how to find the satellite pixel at the center of the region of interest, and so it correctly copies over the OSGB coordinates into the NetCDF file (the OSGB coordinates are required for the ML models to know where each pixel is).

## Context
https://github.com/openclimatefix/Satip/pull/56

## Possible Implementation
It might be simplest for `SatelliteDataSource.get_spatial_region_of_interest` to convert `x_center_osgb` and `y_center_osgb` to geostationary coordinates, and then remove `_osgb` from lines 120 & 121.

Convert from OSGB to Geostationary CRS like this:
```python
# Do this once, after opening the Zarr:
geostationary_area_definition = pyresample.area_config.load_area_from_string(data_array.attrs['area'])
geostationary_crs = geostationary_area_definition.crs
osgb_to_geostationary = pyproj.Transformer.from_crs(crs_from=27700, crs_to=geostationary_crs)

# Then, for each example:
geos_x, geos_y = osgb_to_geostationary(osgb_x, osgb_y)
```

**Comment by peterdudfield** [comment]
Could the new coordinates be called `x_lon` and `x_lat`, or a different unit. It think it was useful to have what coorindates they are, as in the past we (or maybe just me) have got consfused

**Comment by JackKelly** [comment]
The `attrs` for `x` and `y` give the details. But, yeah, you're right that it might be good to rename them. I've added an issue to Satip here: https://github.com/openclimatefix/Satip/issues/62

**Comment by JackKelly** [comment]
The new names won't be in the newly converted data. But they could be in the data that we re-create from the native files.
