### ISSUE TITLE
Save metadata about each dataset to disk

### ISSUE THREAD

**Issue by JackKelly** [openclimatefix/nowcasting_dataset#59]
The `scripts/prepare_ml_training_data.py` should save appropriate metadata with each set of NetCDF files (e.g. history_len, batch_size, the source datasets, etc.)

**Comment by peterdudfield** [comment]
I think these begins to cover it - https://github.com/openclimatefix/nowcasting_dataset/pull/69

**Comment by JackKelly** [comment]
Yup, agreed!  Let's close this issue for now.  Thank you!
