### ISSUE TITLE
Reduce size of hrv sat data

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting_dataset#593]
## Detailed Description
The current hrv sat data in the test folder in 83 MB. The sat data is only 10MB. Could we reduce the size of the hrv data? 

I think this started happening from the version 3.1.49. @JackKelly there was a merge you made to do with 'new-2D-osgb-coords'

This may be linked to #591 

## Context
Better not to commit to much MBs in the code

**Comment by JackKelly** [comment]
> The current hrv sat data in the test folder in 83 MB. The sat data is only 10MB.

Do you mean that each batch of HRV sat data is 83 MB?

That definitely sounds too big!

Do the tests use [`tests/config/test.yaml`](https://github.com/openclimatefix/nowcasting_dataset/blob/main/tests/config/test.yaml)?

Uncompressed, each HRV batch should be 64 x 64 pixels x 2 bytes per pixel x 30 timesteps per example x 32 examples = 7.7 MB.

The new OSGB coords shouldn't change the file size of the batch.

**Comment by JackKelly** [comment]
Oh, wait, sorry, I misunderstood!  You mean `nowcasting_dataset/tests/data/hrv_sat_data.zarr` is 83 MB?

**Comment by JackKelly** [comment]
Yeah, we probably could reduce that a bit. Or maybe we could put our testing data into a publicly accessible GCP bucket or something?

If we reduce the duration of the HRV satellite data then we'd have to change some of the unittests which currently assume the testing HRV and testing satellite data cover the same time periods.

**Comment by jacobbieker** [comment]
Now that the hrv data is public, we could stream it in from there?

**Comment by JackKelly** [comment]
SGTM!

**Comment by peterdudfield** [comment]
yea, I like it aswell. It doesnt I think go against the idea that unittest should be isolated, where this method would mean it relies on having an internet connection.

**Comment by peterdudfield** [comment]
This has been reduced, by using less time steps
