### ISSUE TITLE
Configure data pre-processing with a yaml config file

### ISSUE THREAD

**Issue by JackKelly** [openclimatefix/nowcasting_dataset#60]
The `scripts/prepare_ml_training_data.py` should take in a yaml config file.  These config files can then be stored with the ML model experiments.  Related to #59

Also related: https://github.com/openclimatefix/predict_pv_yield/issues/52

**Comment by peterdudfield** [comment]
Ill have a look at this

**Comment by JackKelly** [comment]
https://github.com/openclimatefix/nowcasting_dataset/pull/69

**Comment by JackKelly** [comment]
Thanks @peterdudfield for implementing this!  Nice work!
