### ISSUE TITLE
Allow for rectangular regions of interest for satellite data

### ISSUE THREAD

**Issue by JackKelly** [openclimatefix/nowcasting_dataset#601]
## Detailed Description
At the moment, we select square ROIs of satellite data (square in pixel space).

But, when projected to OSGB, those "square" images are actually quite tall rectangles. Which isn't ideal because, if anything, we probably want satellite images that are wider than taller (because most winds across the UK are from west to east)

A simple solution would be to allow for rectangular (in pixel space) satellite images, so we can manually request satellite imagery that is, say, 64 pixels tall and 128 pixels wide (which would be rectangular in pixel space, but might be very roughly square in OSGB).

Here are two plots of our satellite imagery at the moment:

Here's a plot in geostationary projection (which shows that the satellite image is square in pixel space):

![image](https://user-images.githubusercontent.com/460756/152327291-8491647d-3ba4-40ea-87d8-7f0f194447df.png)

And here's the exact same data, but now reprojected to OSGB. Note how tall and thin the satellite image is:

![image](https://user-images.githubusercontent.com/460756/152327434-3310b1c7-ebab-4527-a4be-aaf9709861e2.png)

**Comment by JackKelly** [comment]
Interestingly, our HRV batches don't cover exactly the same geographical extent as our PV batches. Here's a plot of HRV imagery and PV systems (in red).

![image](https://user-images.githubusercontent.com/460756/157499120-cd710eca-d816-425d-8423-00b418f85d2e.png)


I think what's going on is that `PVDataSource` calculates its geographical region of interest by multiplying `image_size_pixels=64 x meters_per_pixel=2000`. But each satellite pixel is a "tilted rectangle" which is about 1.3 km wide x 2.5 km high.


This isn't terrible. But I thought I'd flag it up! A quick fix might be to allow for rectangular (in pixel-space) satellite batches

**Comment by jacobbieker** [comment]
I'm starting to work on this! I'm not sure the easiest way to approach it, I was thinking of having the config setup now have a image_size_pixels_height and image_size_pixels_width for the satellite imagery? Slightly less changes would be required for just setting the width to be twice that of image_size_pixels but would be less flexible in the future, any preference @peterdudfield @JackKelly ?

**Comment by peterdudfield** [comment]
i like the idea of 
- image_size_pixels_height
- image_size_pixels_width
but I can see the quick fix of times by 2. 

Perhaps give the height and width ago and if it gets to messy we can take the quick option. 
Happy to do some paired programming on it if you like

**Comment by JackKelly** [comment]
Either option sounds good to me! Thanks guys!

**Comment by jacobbieker** [comment]
Yeah, I'm trying with adding height and width first, as also as we go to other places latitudes, the difference between how tall and how wide each pixel is would change.
