### ISSUE TITLE
Add satellite option to load netcdf

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting_dataset#606]
## Detailed Description
Add satellite option to load netcdf - similar to nwp

## Context
Good for live data to be loaded with the same code as the historic

## Possible Implementation
similar to [nwp](https://github.com/openclimatefix/nowcasting_dataset/blob/main/nowcasting_dataset/data_sources/nwp/nwp_data_source.py#L190)

**Comment by jacobbieker** [comment]
Closing this as its been done with Zarrs still
