### ISSUE TITLE
Use minimal data types for PV

### ISSUE THREAD

**Issue by JackKelly** [openclimatefix/nowcasting_dataset#624]
This is what a PV batch looks like in v15. All the 64-bit data types could be 32-bit:

![image](https://user-images.githubusercontent.com/460756/159941270-d4f0bab8-c5ee-426f-ab0c-b753bddd9bc8.png)

**Comment by peterdudfield** [comment]
Ill have a look at v16, just incase its been done already

**Comment by peterdudfield** [comment]
Looking in `/mnt/storage_ssd_4tb/data/ocf/solar_pv_nowcasting/nowcasting_dataset_pipeline/prepared_ML_training_data/v16/test/pv`

```python
import xarray as xr
pv = xr.load_dataset('000000.nc',engine='h5netcdf')
```
<img width="898" alt="Screenshot 2022-04-07 at 13 43 23" src="https://user-images.githubusercontent.com/34686298/162422927-06f0c9a6-526d-4d22-8b0e-9cf7087a5374.png">

so the varibales that need upgrading are
- x_coords -> float32
- y_coords -> float32
- id -> int32

**Comment by JackKelly** [comment]
sounds good!

I think we need to use `float32` for `id` (so we can use an ID value of `NaN` to represent "missing" PV systems)

Also, I think we can completely throw away `example_index`, `id_index`, and `time_index` because they're just repeats of the `example`, `id`, and `time` dimensions :slightly_smiling_face:  Please see issues #629 and #630 for more context on throwing away `example_index`, `id_index`, and `time_index`.
