### ISSUE TITLE
Change channel order for all satellite data

### ISSUE THREAD

**Issue by JackKelly** [openclimatefix/nowcasting_dataset#628]
We could add something like this:

```python
SATELLITE_CHANNEL_ORDER = (
    "example",
    "time_index",
    "channels_index",
    "y_geostationary_index",
    "x_geostationary_index",
)

dataset["data"] = dataset["data"].transpose(*SATELLITE_CHANNEL_ORDER)
```

**Comment by peterdudfield** [comment]
In `nowcasting_dataloader` we have https://github.com/openclimatefix/nowcasting_dataloader/blob/main/nowcasting_dataloader/data_sources/satellite/satellite_model.py#L95, but this could aslo be done here

**Comment by JackKelly** [comment]
yeah, in general, it'd be great if the dataloader has to do as little work as possible (both to simplify the code, and to make it run as quickly as possible). But, that said, this isn't super-urgent. Transposing the channel order on-the-fly in the dataloader is super-fast, so it's not a bit deal :slightly_smiling_face:
