### ISSUE TITLE
`Sun` should probably save `elevation` and `azimuth` as `float32` not `int64`

### ISSUE THREAD

**Issue by JackKelly** [openclimatefix/nowcasting_dataset#634]

**Comment by peterdudfield** [comment]
Is this in the batches or in the data source

**Comment by JackKelly** [comment]
My proposal is that the on-disk batches should save `elevation` and `azimuth` as `float32`. Otherwise it gets quantized into integer increments :slightly_smiling_face:

**Comment by peterdudfield** [comment]
Yea i was just wondering if its saved liked that in the main data source, or its done in the batches - ill have a look

**Comment by peterdudfield** [comment]
I found it, it was in the main data source, I will adjust the script and rerun
