### ISSUE TITLE
Collect 6 hours of future gsp data

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting_dataset#636]
## Detailed Description
MVP should predict forward 6 hours into the future, so lets make sure the next batch has this data available

## Possible Implementation
Change GSP future minutes to 360 in config

**Comment by peterdudfield** [comment]
duplicate of this - https://github.com/openclimatefix/nowcasting_dataset/issues/572

**Comment by peterdudfield** [comment]
Could just extend v15 GSP data to 4 hours out. 

This then makes use of the fact our data sources are module

**Comment by JackKelly** [comment]
* Sat: 2 hours into the future
* NWP & GSP & PV: 6 hours into the future
