### ISSUE TITLE
Fix unit tests

### ISSUE THREAD

**Issue by JackKelly** [openclimatefix/nowcasting_dataset#64]

**Comment by peterdudfield** [comment]
Done, but not committed. Add 'convert_to_numpy=True' to https://github.com/openclimatefix/nowcasting_dataset/blob/3e418c769ed48070dd64b68b7f8cefa899383783/conftest.py#L36

This will only test if 'convert_to_numpy=True' is working, perhaps (but might be over kill) is to write some convert_to_numpy=False' tests

**Comment by JackKelly** [comment]
Is this issue closed by https://github.com/openclimatefix/nowcasting_dataset/pull/68 and https://github.com/openclimatefix/nowcasting_dataset/pull/66 ?   :)
