### ISSUE TITLE
Add automatic testing

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting_dataset#67]
Add automatic tests for everytime a 'push' is made. 

Suggestion to use github actions, as its free for public github repos, and less over head than other CD services.

**Comment by jacobbieker** [comment]
You could look at this, its what I do in Satflow to run all tests with pytest on every push: https://github.com/openclimatefix/satflow/blob/main/.github/workflows/workflows.yaml

**Comment by peterdudfield** [comment]
Thanks @jacobbieker, yea got that working. Just fixing a funny test with pyproj now ....

**Comment by JackKelly** [comment]
Great work!  Thanks for getting automated testing working for `nowcasting_dataset`, @peterdudfield!
