### ISSUE TITLE
GSP locations might have changed since v15 was created

### ISSUE THREAD

**Issue by jacobbieker** [openclimatefix/nowcasting_dataset#672]
**Describe the bug**
In trying to regenerate the GSP data for v15 with  8 hours into the future data, the test dataset has had quite a few isssues. One of them seems to be that there is no GSP at the exact spatial location specified in the spatial_and_temporal_locations. My understanding is that these locations come frrom the GSP locations, so this shouldn't be possible, unless a GSP got moved? Or the location got rounded somehow.

The train examples get generated correctly, so not sure why the test ones do not.

**To Reproduce**

Run nowcasting_dataset with the v15 config

```
NotImplementedError: Not yet implemented the ability to find GSP *nearest* (but not at the identical location to) x_center_osgb and y_center_osgb. Metadata:         Unnamed: 0  _id  ...     location_x     location_y
gsp_id                   ...                              
1.0              0    1  ...  448890.850878  206989.968190
2.0              1    2  ...  472006.957122  237636.958066
3.0              2    3  ...  451522.450933  306028.459849
4.0              3    4  ...  483799.511974  285796.610471
5.0              4    5  ...  459869.681140  324201.751399
...            ...  ...  ...            ...            ...
334.0          371  372  ...  374787.487709  164683.048231
335.0          376  377  ...  435627.877515  469959.621069
336.0          377  378  ...  233134.898944  374044.047565
337.0          378  379  ...  261506.592133  661584.355091
338.0          379  380  ...  256896.514372  666179.699987

[307 rows x 30 columns] X_OSGB: 274259.9948591415, y_center_osgb=60584.11230625189
NoneType: None
```

**Expected behavior**

The GSP examples get created.

**Additional context**

**Comment by JackKelly** [comment]
Nice fix!

Did we ever get to the bottom of why this was failing in the first place? (i.e. why the GSP locations couldn't be found by exact match?) That sounds a little worrying to me!

**Comment by jacobbieker** [comment]
No I didn't. I ran a fresh dataset of gsp locations for 16000 train /3000 val/3000 test batches and there were no errors for NaNs or anything and it finished successfully. But yeah, don't know why the locations changed at all between then and now. Running the original config with the same version of dataset as the original also lead to being unable to find the exact match, so I think it's just because the ESO data got slightly updated possibly?
