### ISSUE TITLE
`hrv_satellite_fake` should return the requested `image_size_pixels`, not `3 x image_size_pixels`

### ISSUE THREAD

**Issue by JackKelly** [openclimatefix/nowcasting_dataset#693]
**Describe the bug**
If you ask `hrv_satellite_fake` for an image 256 pixels wide by 128 pixels high then it'll return an image of shape 768 wide x 384 high.

Which, presumably, is because of the `* 3` on lines 376 & 377 of `batch.py`:

![image](https://user-images.githubusercontent.com/460756/176222147-2ead9142-3f08-416e-89e2-b2f51b645b1a.png)

@peterdudfield is it safe to simply remove the `* 3` from those lines? :slightly_smiling_face: 

Yes, the HRV images are higher resolution than the other satellite channels. But the `configuration` requests the image size in _pixels_, so, if I've understood correctly, the HRV images should always be exactly the pixel sizes that were requested in the config?

**Comment by peterdudfield** [comment]
Yea, you can remove the *3. Sorry about that
