### ISSUE TITLE
Fake `hrvsatellite` and `satellite` batches need 2D osgb coords

### ISSUE THREAD

**Issue by JackKelly** [openclimatefix/nowcasting_dataset#695]
At the moment, `nowcasting_dataset.data_sources.fake.batch.create_image_array` creates fake satellite data with 1D `x_geostationary` and `y_geostationary` coords. We also need 2D `x_osgb` and `y_osgb` coords.

I just wanted to check with you, @peterdudfield, that this change won't break too many things?!

**Comment by peterdudfield** [comment]
If thats the way the new batch is then we should use that. When we generate batches are they in 2D?

**Comment by JackKelly** [comment]
> When we generate batches are they in 2D?

Yes, the pre-prepared batches on disk (created by `prepare_ml_data.py`) have 2D OSGB coords.
