### ISSUE TITLE
Split train and valid data properly

### ISSUE THREAD

**Issue by JackKelly** [openclimatefix/nowcasting_dataset#7]

**Comment by JackKelly** [comment]
Maybe use the first day of each month?

Need to think how to ensure the Dataset always uses exactly the same datetimes and PV systems everytime the val data is requested.

And see if it's easy to ask Dask to persist the val data in mem

**Comment by JackKelly** [comment]
On 2nd thoughts, maybe we should split the dataset into weeks, and validate on every 5th week, or something like that?  Ensure the boundaries are at day boundaries (to avoid allowing some validation data into the train set).

This scheme is probably not standard in the forecasting community, but it's nicer than training on the first 4/5th and validating on the last 5th, because - while our dataset is only 1.5 years - we want to validate across all seasons.

**Comment by peterdudfield** [comment]
Ive moved this to https://github.com/openclimatefix/nowcasting_utils/issues/16

**Comment by JackKelly** [comment]
Cool beans!  (Just for those following along at home... we've decided to move the issue Peter linked to above back into `nowcasting_dataset`: #127, so I'll make this issue as a duplicate and close it!)
