### ISSUE TITLE
Save data to AWS

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting_dataset#71]
Current data is being saved to gcs, but would be good to have option to save to AWS aswell. This means we could then use VM's with AWS as well as GCP. 

Would need to have option for saving to AWS, and also option for loading from AWS

**Comment by JackKelly** [comment]
In terms of getting our training data onto AWS:

I downloaded the NWP & satellite data onto my local workstation from GCS.  When I'm back from Spain, I can upload this data to AWS, so we can run `nowcasting_dataset` from an AWS VM, using source data from S3, and outputting the prepared dataset to S3 :)
