### ISSUE TITLE
Out of date link

### ISSUE THREAD

**Issue by devsjc** [openclimatefix/nowcasting_dataset#723]
https://github.com/openclimatefix/nowcasting_dataset/blob/658d2fb0487e26256cd25b6d1ecc1d54d75ecb2a/nowcasting_dataset/data_sources/nwp/nwp_data_source.py#L31

The above line no longer references the PDF source correctly - it seems it now exists at https://zenodo.org/record/7357056

**Comment by JackKelly** [comment]
Thank you for flagging this issue! I've updated the Python file!
