### ISSUE TITLE
Remove PyTorch from the code

### ISSUE THREAD

**Issue by JackKelly** [openclimatefix/nowcasting_dataset#86]
When I started `nowcasting_dataset`, the intention was to use `nowcasting_dataset` to generate batches on-the-fly during ML training from separate Zarr stores for the satellite data, NWPs, and PV.  But that turned out to be too slow and fragile :)  So, we swapped to using `nowcasting_dataset` to pre-prepare batches ahead-of-time, and save them to disk.   During ML training, we just need to load the batches from disk, and we're good-to-go.  (Pre-preparing batches has a number of other advantages, too).

But, this development history means that `nowcasting_dataset` still uses PyTorch (e.g. using the PyTorch DataLoader to run multiple processes).  The code may become cleaner and faster and more flexible if we strip out PyTorch, and instead (maybe) use [`concurrent.futures.ProcessPoolExecutor`](https://docs.python.org/3/library/concurrent.futures.html#processpoolexecutor) to use multiple processes.

TODO:

- [x] Remove Datasets and Datamodule.  Done in PR #307 
- [x] Remove pytorch lightning from requirements.txt and environment.yaml.  Done in PR #307.
- [ ] Remove torch from other python files
- [ ] Remove torch from requirements.txt and environment.yaml

**Comment by peterdudfield** [comment]
https://github.com/openclimatefix/nowcasting_dataset/issues/213#issuecomment-939807558
from big issue

Idea is to use optional requirements for pytorch

**Comment by JackKelly** [comment]
If it's OK, I'll keep this issue open until we've removed the pytorch dataloader and pytorch lightning from the "batch pre-processing" code :)

**Comment by peterdudfield** [comment]
Maybe its not quite closed, would be good to remove it from requirements too

**Comment by JackKelly** [comment]
Oops, you're exactly right, sorry - this issue should still be open!

**Comment by JackKelly** [comment]
FWIW, these are the places where "torch" is still mentioned in our code: 
![image](https://user-images.githubusercontent.com/460756/139920049-1611b2a2-4ea4-4c4c-b06f-1e6391b38aa2.png)
