### ISSUE TITLE
Add GSP-level Regional PV Live data into the dataset

### ISSUE THREAD

**Issue by JackKelly** [openclimatefix/nowcasting_dataset#88]
Following on from #79  (thanks loads, @peterdudfield, for collecting this GSP PV data!  It's awesome to see this data come to life.)

I guess a next steps is to include the GSP PV Live data in nowcasting_dataset.  Just thinking aloud about one way to do this:

At the moment, the target for every training example is the PV yield of the PV system in the center of the square of satellite imagery.

To include GSP PV yield:

In a configurable proportion of the training examples (say, 20%), the target "PV yield" should be the PV yield for a GSP region, and we should set a flag to tell the model that we want it to predict PV yield for a GSP region, not an individual PV system.  The satellite imagery could be centred on the centroid of the GSP region (GeoPandas can calculate the centroid of regions).  (Is centroid the right geometric point?)  Each GSP region should also have a unique "PV system ID", so the model stands a chance of learning the qualities of the different GSP regions.

For the model to learn to infer PV yield for entire GSP regions, we probably also need to implement #87.

**Comment by peterdudfield** [comment]
Might want to help the model out, but telling it which pv systems are in the GSP, and which arent.

**Comment by JackKelly** [comment]
Oooh, great point!  You're absolutely right!

**Comment by peterdudfield** [comment]
As discussed with @JackKelly 

Start with a simple dataset which contains
- GSP pv yield data, might need metadata too
- sat images or that region
- nwp images, just take center point of view
- pv system data in that area of interest, might be good to have a flag if the pv system is in that gsp or not
- time sin cos variables

**Comment by JackKelly** [comment]
Just because my memory is so awful (!)... Just making a note that, for the "simple dataset", we decided that the ML target will _always_ be GSP-level PV.  The _input_ the ML model will include GSP-level PV as well as single-PV-system data.

**Comment by peterdudfield** [comment]
@JackKelly what would advise on forecast and history length. This is slightly more complicated now as we have 5min satallite data and 30 mins GSP data.

I was thinking Still loading 30mins back, and 1 hour forward and for the different data sets that will mean a different amount of snapshots. That sounds about right?

**Comment by JackKelly** [comment]
Good questions!

I'd expect the models will want more like an hour of recent history in each example saved to disk.  The ML model can always choose to ignore the first half an hour if necessary.

A forecast horizon of 1 hour into the future is fine for now.  In the next month or so we'll probably want to start experimenting with slightly longer forecasts (maybe up to 4 hours ahead?)

In the ideal case, we'd get Sheffield Solar's 5-minutely estimates for GSP-level PV generation, so everything lines up nicely :)

**Comment by peterdudfield** [comment]
Yea good point, 

Ill keep going for now, and maybe it'll become easier when everything is 5 mins data

**Comment by JackKelly** [comment]
Another random thought... Another nice thing about fully-attentional models is that the different input modalities (PV power; satellite imagery; NWPs; etc) don't need to be perfectly aligned in time or space; and don't need to be exactly the same sample rate.  But, for now, we should probably ignore that (!) and stick with ML examples which are as aligned as possible (not least because that allows us to train different models using the same data).

**Comment by peterdudfield** [comment]
My understanding was not to put this in https://github.com/orgs/openclimatefix/projects/2#card-69441934. @JackKelly that right?

**Comment by JackKelly** [comment]
I think we can close this issue now.  What do you think @peterdudfield ?  I'll close it for now.  Please feel free to re-open if I've misunderstood!
