### ISSUE TITLE
Implement script to download data from EUMETSAT Data Store

### ISSUE THREAD

**Issue by JackKelly** [openclimatefix/nowcasting_dataset#91]
https://www.eumetsat.int/eumetsat-data-store

Required behaviour when the script runs:

1. Check what data is already downloaded to disk (e.g. maybe all data for 2020-01 and 2020-06 is already downloaded, so we don't need to download those two months of data again.)
2. If the script is called with the `--backfill` flag then download any missing data between the start date of the data available from EUMETSAT and the end-date of the downloaded data.  (e.g. download 2010 to 2019-12-31; and download 2020-02-01 to 2020-05-30)
3. If the `--backfill` flag is not set then just download any missing new data.

For now, we just want the EUMETSAT SEVIRI RSS data (full spatial extent, and all timesteps).  In the future, we may want other EUMETSAT data products.

Download concurrently using multiple threads.

While the file is downloading, append `partial` to the filename.  Only remove the `partial` once the file has fully downloaded and passes all sanity checks (so, if the script crashes part way through a download, it's clear which files are partially downloaded and should be deleted!)

Log download progress.  

If possible, allow the user to limit the download rate (so I can still watch Netflix whilst downloading EUMETSAT data!)

Don't bother with spatial re-projection yet (that will be done when nowcasting_dataset is run).

@jacobbieker is your EUMETSAT data ingestion script on GitHub?  (No worries if not!)  If it is, please could you point us to it?

Maybe _don't_ compress as `.bz2` because that forces us to load the entire `.bz2` file off disk and decompress it, even if we only want a small chunk.

Related issues:

* #95 
* #81

**Comment by jacobbieker** [comment]
Its here: https://github.com/openclimatefix/satflow/blob/2be1708bb37916d23ffcf18dd1a1cfd6a709acf5/satflow/data/download.py#L179-L206 using a slightly modified version of https://github.com/openclimatefix/Satip/tree/bug-fix That code downloads the binary cloud mask product as well

**Comment by JackKelly** [comment]
Hi @jacobbieker do you have any plans for how the script will store the raw EUMETSAT data on disk?  Maybe a simple directory structure like `<year>/<month>/<day>/<files>`?  I have no strong feelings either way!

I had previously used `<year>/<month>/<day>/<hour>/<minute of data acquisition>` but I think that's too many levels!  And I had previous compressed the raw files as `bzip2` but I now think that's a bad idea because that forces us to load and decompress the entire file, even if we only want a small subset of the file.

**Comment by jacobbieker** [comment]
Hi, I was thinking just `<year>/<month>/<day>/<files>` would be sufficient enough, its easy enough to get the datetime of the file from the name that its not a big deal. Thanks for the documentation! Would we want to download all data for each day, or just the data for the daytime? For SatFlow I did the 12 hours between 8am and 8pm to roughly get the daytime data only, but not sure if we just want to grab everything for every day or not. I'd lean towards just grabbing everything so we have the data to use for the history timesteps for the morning hours at least

**Comment by JackKelly** [comment]
Yeah, let's grab everything :)

**Comment by jacobbieker** [comment]
Just as a comment: The Cloud masks for RSS only goes back to 2018 apparently: https://eumetsatspace.atlassian.net/wiki/spaces/DSDS/pages/320569418/Current+Data+Store+catalogue so before 2018 there are cloud masks, but only for the 15 minute resolution ones.
