### ISSUE TITLE
Remove hash from NetCDF filenames

### ISSUE THREAD

**Issue by JackKelly** [openclimatefix/nowcasting_dataset#99]
`nowcasting_dataset` produces ML batches.  Each batch is stored in a separate NetCDF file.  The filename for each NetCDF file includes a hash.  e.g. the filename `000776_8509.nc` is made up for a hash (`000776`) and the batch number (`8509`).  I included a hash because the Google Cloud documentation says you can get slightly higher throughput by including a hash in the filename, to maximise the chance that your files are distributed across multiple storage nodes.

But the hash makes the filenames harder for humans to read.  And it's not clear that the extra performance is relevant for us.  And, we're about to do most of our ML research on our own hardware (which doesn't benefit from hashing).  So maybe we should remove the hash from the filename?

Any opinions, anyone?!

**Comment by peterdudfield** [comment]
Yea happy to get rid of it 

or, we could make the hash with a configuration file - this means it would make sure it loads the batch with the correct config file. However I think this i slightly complicated, and not really needed - for now

**Comment by jacobbieker** [comment]
Yeah, I agree with @peterdudfield potentially make it a hash of the config, but if not, then yeah, might as well get rid of it.

**Comment by JackKelly** [comment]
Good ideas!

But, yeah, for now, I'd vote to keep thing simple and get rid of the hash. 

If we find it really hurts performance on cloud storage buckets then it's easy to add back in.
